// Generated by scripts/generate-schema-module.mjs. Do not edit directly.

export const GENERATED_RUNTIME_RECORD_SCHEMAS: Record<string, Record<string, unknown>> = {
  "runtime_workflow": {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "title": "mdbase durable runtime workflow",
    "type": "object",
    "required": [
      "type",
      "id",
      "version",
      "name",
      "enabled",
      "triggers",
      "steps"
    ],
    "properties": {
      "type": {
        "const": "runtime_workflow"
      },
      "id": {
        "type": "string",
        "pattern": "^[A-Za-z][A-Za-z0-9._:-]*$"
      },
      "version": {
        "type": "string",
        "pattern": "^(0|[1-9][0-9]*)\\.(0|[1-9][0-9]*)\\.(?:0|[1-9][0-9]*)(?:-[0-9A-Za-z-]+(?:\\.[0-9A-Za-z-]+)*)?(?:\\+[0-9A-Za-z-]+(?:\\.[0-9A-Za-z-]+)*)?$"
      },
      "name": {
        "type": "string",
        "minLength": 1
      },
      "description": {
        "type": "string"
      },
      "enabled": {
        "type": "boolean"
      },
      "requires": {
        "$ref": "#/$defs/requires"
      },
      "vars": {
        "type": "object",
        "additionalProperties": {}
      },
      "triggers": {
        "type": "array",
        "minItems": 1,
        "items": {
          "$ref": "#/$defs/trigger"
        }
      },
      "steps": {
        "type": "array",
        "minItems": 1,
        "items": {
          "$ref": "#/$defs/step"
        }
      },
      "run": {
        "$ref": "#/$defs/runPolicy"
      }
    },
    "patternProperties": {
      "^x-[A-Za-z0-9._:-]+$": true
    },
    "additionalProperties": false,
    "$defs": {
      "identifier": {
        "type": "string",
        "pattern": "^[A-Za-z][A-Za-z0-9._:-]*$"
      },
      "semanticVersion": {
        "type": "string",
        "pattern": "^(0|[1-9][0-9]*)\\.(0|[1-9][0-9]*)\\.(?:0|[1-9][0-9]*)(?:-[0-9A-Za-z-]+(?:\\.[0-9A-Za-z-]+)*)?(?:\\+[0-9A-Za-z-]+(?:\\.[0-9A-Za-z-]+)*)?$"
      },
      "digest": {
        "type": "string",
        "pattern": "^sha256:[0-9a-f]{64}$"
      },
      "dateTime": {
        "type": "string",
        "format": "date-time"
      },
      "contractRequirement": {
        "type": "object",
        "required": [
          "id",
          "version"
        ],
        "properties": {
          "id": {
            "type": "string",
            "pattern": "^[A-Za-z][A-Za-z0-9._:-]*$"
          },
          "version": {
            "type": "string",
            "minLength": 1
          },
          "digest": {
            "type": "string",
            "pattern": "^sha256:[0-9a-f]{64}$"
          }
        },
        "patternProperties": {
          "^x-[A-Za-z0-9._:-]+$": true
        },
        "additionalProperties": false
      },
      "exactContractReference": {
        "type": "object",
        "required": [
          "id",
          "version",
          "digest"
        ],
        "properties": {
          "id": {
            "type": "string",
            "pattern": "^[A-Za-z][A-Za-z0-9._:-]*$"
          },
          "version": {
            "type": "string",
            "pattern": "^(0|[1-9][0-9]*)\\.(0|[1-9][0-9]*)\\.(?:0|[1-9][0-9]*)(?:-[0-9A-Za-z-]+(?:\\.[0-9A-Za-z-]+)*)?(?:\\+[0-9A-Za-z-]+(?:\\.[0-9A-Za-z-]+)*)?$"
          },
          "digest": {
            "type": "string",
            "pattern": "^sha256:[0-9a-f]{64}$"
          }
        },
        "patternProperties": {
          "^x-[A-Za-z0-9._:-]+$": true
        },
        "additionalProperties": false
      },
      "identity": {
        "type": "object",
        "required": [
          "application",
          "implementation",
          "version"
        ],
        "properties": {
          "application": {
            "type": "string",
            "pattern": "^[A-Za-z][A-Za-z0-9._:-]*$"
          },
          "implementation": {
            "type": "string",
            "pattern": "^[A-Za-z][A-Za-z0-9._:-]*$"
          },
          "version": {
            "type": "string",
            "pattern": "^(0|[1-9][0-9]*)\\.(0|[1-9][0-9]*)\\.(?:0|[1-9][0-9]*)(?:-[0-9A-Za-z-]+(?:\\.[0-9A-Za-z-]+)*)?(?:\\+[0-9A-Za-z-]+(?:\\.[0-9A-Za-z-]+)*)?$"
          },
          "instance_id": {
            "type": "string",
            "minLength": 1
          }
        },
        "patternProperties": {
          "^x-[A-Za-z0-9._:-]+$": true
        },
        "additionalProperties": false
      },
      "providerSelector": {
        "type": "object",
        "required": [],
        "properties": {
          "application": {
            "type": "string",
            "pattern": "^[A-Za-z][A-Za-z0-9._:-]*$"
          },
          "implementation": {
            "type": "string",
            "pattern": "^[A-Za-z][A-Za-z0-9._:-]*$"
          },
          "instance_id": {
            "type": "string",
            "minLength": 1
          }
        },
        "patternProperties": {
          "^x-[A-Za-z0-9._:-]+$": true
        },
        "additionalProperties": false,
        "minProperties": 1
      },
      "expression": {
        "type": "object",
        "required": [
          "$expr"
        ],
        "properties": {
          "$expr": {
            "type": "string",
            "minLength": 1
          }
        },
        "additionalProperties": false
      },
      "requires": {
        "type": "object",
        "required": [],
        "properties": {
          "capabilities": {
            "type": "array",
            "uniqueItems": true,
            "items": {
              "type": "string",
              "pattern": "^[A-Za-z][A-Za-z0-9._:-]*$"
            }
          }
        },
        "patternProperties": {
          "^x-[A-Za-z0-9._:-]+$": true
        },
        "additionalProperties": false
      },
      "trigger": {
        "type": "object",
        "required": [
          "id",
          "event"
        ],
        "properties": {
          "id": {
            "type": "string",
            "pattern": "^[A-Za-z][A-Za-z0-9._:-]*$"
          },
          "event": {
            "$ref": "#/$defs/contractRequirement"
          },
          "if": {
            "type": "object",
            "required": [
              "$expr"
            ],
            "properties": {
              "$expr": {
                "type": "string",
                "minLength": 1
              }
            },
            "additionalProperties": false
          },
          "debounce": {
            "$ref": "#/$defs/duration"
          },
          "minimum_interval": {
            "$ref": "#/$defs/duration"
          }
        },
        "patternProperties": {
          "^x-[A-Za-z0-9._:-]+$": true
        },
        "additionalProperties": false
      },
      "step": {
        "type": "object",
        "required": [
          "id",
          "action"
        ],
        "properties": {
          "id": {
            "type": "string",
            "pattern": "^[A-Za-z][A-Za-z0-9._:-]*$"
          },
          "name": {
            "type": "string"
          },
          "action": {
            "$ref": "#/$defs/contractRequirement"
          },
          "provider": {
            "$ref": "#/$defs/providerSelector"
          },
          "requires": {
            "$ref": "#/$defs/requires"
          },
          "if": {
            "type": "object",
            "required": [
              "$expr"
            ],
            "properties": {
              "$expr": {
                "type": "string",
                "minLength": 1
              }
            },
            "additionalProperties": false
          },
          "input": {
            "type": "object",
            "additionalProperties": {}
          },
          "for_each": {
            "type": "object",
            "required": [
              "items"
            ],
            "properties": {
              "items": {},
              "as": {
                "type": "string",
                "pattern": "^[A-Za-z_][A-Za-z0-9_]*$"
              }
            },
            "patternProperties": {
              "^x-[A-Za-z0-9._:-]+$": true
            },
            "additionalProperties": false
          }
        },
        "patternProperties": {
          "^x-[A-Za-z0-9._:-]+$": true
        },
        "additionalProperties": false
      },
      "duration": {
        "type": "string",
        "pattern": "^(0|[1-9][0-9]*)(ms|s|m|h|d)$"
      },
      "runPolicy": {
        "type": "object",
        "required": [],
        "properties": {
          "idempotency": {
            "type": "object",
            "required": [
              "key"
            ],
            "properties": {
              "key": {}
            },
            "patternProperties": {
              "^x-[A-Za-z0-9._:-]+$": true
            },
            "additionalProperties": false
          },
          "concurrency": {
            "type": "object",
            "required": [
              "policy"
            ],
            "properties": {
              "group": {},
              "policy": {
                "enum": [
                  "skip",
                  "queue",
                  "replace",
                  "allow"
                ]
              }
            },
            "patternProperties": {
              "^x-[A-Za-z0-9._:-]+$": true
            },
            "additionalProperties": false
          },
          "limits": {
            "type": "object",
            "required": [],
            "properties": {
              "timeout": {
                "$ref": "#/$defs/duration"
              },
              "max_items": {
                "type": "integer",
                "minimum": 1
              }
            },
            "patternProperties": {
              "^x-[A-Za-z0-9._:-]+$": true
            },
            "additionalProperties": false
          },
          "on_error": {
            "enum": [
              "stop",
              "continue"
            ]
          }
        },
        "patternProperties": {
          "^x-[A-Za-z0-9._:-]+$": true
        },
        "additionalProperties": false
      }
    },
    "$id": "https://mdbase.dev/schemas/runtime/v0.2/mdbase.runtime.workflow/1.0.0.schema.json"
  },
  "runtime_policy": {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "title": "mdbase durable runtime policy",
    "type": "object",
    "required": [
      "type",
      "id",
      "version",
      "enabled",
      "grants"
    ],
    "properties": {
      "type": {
        "const": "runtime_policy"
      },
      "id": {
        "type": "string",
        "pattern": "^[A-Za-z][A-Za-z0-9._:-]*$"
      },
      "version": {
        "type": "string",
        "pattern": "^(0|[1-9][0-9]*)\\.(0|[1-9][0-9]*)\\.(?:0|[1-9][0-9]*)(?:-[0-9A-Za-z-]+(?:\\.[0-9A-Za-z-]+)*)?(?:\\+[0-9A-Za-z-]+(?:\\.[0-9A-Za-z-]+)*)?$"
      },
      "name": {
        "type": "string",
        "minLength": 1
      },
      "enabled": {
        "type": "boolean"
      },
      "executors": {
        "type": "object",
        "required": [],
        "properties": {
          "default": {
            "type": "string",
            "pattern": "^[A-Za-z][A-Za-z0-9._:-]*$"
          },
          "workflows": {
            "type": "object",
            "additionalProperties": {
              "type": "string",
              "pattern": "^[A-Za-z][A-Za-z0-9._:-]*$"
            }
          }
        },
        "patternProperties": {
          "^x-[A-Za-z0-9._:-]+$": true
        },
        "additionalProperties": false
      },
      "provider_selections": {
        "type": "array",
        "items": {
          "type": "object",
          "required": [
            "contract",
            "selector"
          ],
          "properties": {
            "contract": {
              "$ref": "#/$defs/contractRequirement"
            },
            "selector": {
              "$ref": "#/$defs/providerSelector"
            }
          },
          "patternProperties": {
            "^x-[A-Za-z0-9._:-]+$": true
          },
          "additionalProperties": false
        }
      },
      "grants": {
        "type": "array",
        "items": {
          "type": "object",
          "required": [
            "capability",
            "mode"
          ],
          "properties": {
            "capability": {
              "type": "string",
              "pattern": "^[A-Za-z][A-Za-z0-9._:-]*$"
            },
            "mode": {
              "enum": [
                "allow",
                "deny"
              ]
            },
            "actions": {
              "type": "array",
              "uniqueItems": true,
              "items": {
                "$ref": "#/$defs/contractRequirement"
              }
            },
            "providers": {
              "type": "array",
              "uniqueItems": true,
              "items": {
                "$ref": "#/$defs/providerSelector"
              }
            },
            "max_calls_per_run": {
              "type": "integer",
              "minimum": 1
            },
            "max_records_per_run": {
              "type": "integer",
              "minimum": 1
            }
          },
          "patternProperties": {
            "^x-[A-Za-z0-9._:-]+$": true
          },
          "additionalProperties": false
        }
      }
    },
    "patternProperties": {
      "^x-[A-Za-z0-9._:-]+$": true
    },
    "additionalProperties": false,
    "$defs": {
      "identifier": {
        "type": "string",
        "pattern": "^[A-Za-z][A-Za-z0-9._:-]*$"
      },
      "semanticVersion": {
        "type": "string",
        "pattern": "^(0|[1-9][0-9]*)\\.(0|[1-9][0-9]*)\\.(?:0|[1-9][0-9]*)(?:-[0-9A-Za-z-]+(?:\\.[0-9A-Za-z-]+)*)?(?:\\+[0-9A-Za-z-]+(?:\\.[0-9A-Za-z-]+)*)?$"
      },
      "digest": {
        "type": "string",
        "pattern": "^sha256:[0-9a-f]{64}$"
      },
      "dateTime": {
        "type": "string",
        "format": "date-time"
      },
      "contractRequirement": {
        "type": "object",
        "required": [
          "id",
          "version"
        ],
        "properties": {
          "id": {
            "type": "string",
            "pattern": "^[A-Za-z][A-Za-z0-9._:-]*$"
          },
          "version": {
            "type": "string",
            "minLength": 1
          },
          "digest": {
            "type": "string",
            "pattern": "^sha256:[0-9a-f]{64}$"
          }
        },
        "patternProperties": {
          "^x-[A-Za-z0-9._:-]+$": true
        },
        "additionalProperties": false
      },
      "exactContractReference": {
        "type": "object",
        "required": [
          "id",
          "version",
          "digest"
        ],
        "properties": {
          "id": {
            "type": "string",
            "pattern": "^[A-Za-z][A-Za-z0-9._:-]*$"
          },
          "version": {
            "type": "string",
            "pattern": "^(0|[1-9][0-9]*)\\.(0|[1-9][0-9]*)\\.(?:0|[1-9][0-9]*)(?:-[0-9A-Za-z-]+(?:\\.[0-9A-Za-z-]+)*)?(?:\\+[0-9A-Za-z-]+(?:\\.[0-9A-Za-z-]+)*)?$"
          },
          "digest": {
            "type": "string",
            "pattern": "^sha256:[0-9a-f]{64}$"
          }
        },
        "patternProperties": {
          "^x-[A-Za-z0-9._:-]+$": true
        },
        "additionalProperties": false
      },
      "identity": {
        "type": "object",
        "required": [
          "application",
          "implementation",
          "version"
        ],
        "properties": {
          "application": {
            "type": "string",
            "pattern": "^[A-Za-z][A-Za-z0-9._:-]*$"
          },
          "implementation": {
            "type": "string",
            "pattern": "^[A-Za-z][A-Za-z0-9._:-]*$"
          },
          "version": {
            "type": "string",
            "pattern": "^(0|[1-9][0-9]*)\\.(0|[1-9][0-9]*)\\.(?:0|[1-9][0-9]*)(?:-[0-9A-Za-z-]+(?:\\.[0-9A-Za-z-]+)*)?(?:\\+[0-9A-Za-z-]+(?:\\.[0-9A-Za-z-]+)*)?$"
          },
          "instance_id": {
            "type": "string",
            "minLength": 1
          }
        },
        "patternProperties": {
          "^x-[A-Za-z0-9._:-]+$": true
        },
        "additionalProperties": false
      },
      "providerSelector": {
        "type": "object",
        "required": [],
        "properties": {
          "application": {
            "type": "string",
            "pattern": "^[A-Za-z][A-Za-z0-9._:-]*$"
          },
          "implementation": {
            "type": "string",
            "pattern": "^[A-Za-z][A-Za-z0-9._:-]*$"
          },
          "instance_id": {
            "type": "string",
            "minLength": 1
          }
        },
        "patternProperties": {
          "^x-[A-Za-z0-9._:-]+$": true
        },
        "additionalProperties": false,
        "minProperties": 1
      },
      "expression": {
        "type": "object",
        "required": [
          "$expr"
        ],
        "properties": {
          "$expr": {
            "type": "string",
            "minLength": 1
          }
        },
        "additionalProperties": false
      }
    },
    "$id": "https://mdbase.dev/schemas/runtime/v0.2/mdbase.runtime.policy/1.0.0.schema.json"
  },
  "runtime_provider_registration": {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "title": "mdbase runtime provider registration evidence",
    "type": "object",
    "required": [
      "type",
      "id",
      "declaration_kind",
      "declaration",
      "verified_at",
      "active"
    ],
    "properties": {
      "type": {
        "const": "runtime_provider_registration"
      },
      "id": {
        "type": "string",
        "pattern": "^[A-Za-z][A-Za-z0-9._:-]*$"
      },
      "declaration_kind": {
        "enum": [
          "event_source",
          "action_provider"
        ]
      },
      "declaration": {
        "type": "object"
      },
      "verified_at": {
        "type": "string",
        "format": "date-time"
      },
      "active": {
        "type": "boolean"
      }
    },
    "patternProperties": {
      "^x-[A-Za-z0-9._:-]+$": true
    },
    "additionalProperties": false,
    "$defs": {
      "identifier": {
        "type": "string",
        "pattern": "^[A-Za-z][A-Za-z0-9._:-]*$"
      },
      "semanticVersion": {
        "type": "string",
        "pattern": "^(0|[1-9][0-9]*)\\.(0|[1-9][0-9]*)\\.(?:0|[1-9][0-9]*)(?:-[0-9A-Za-z-]+(?:\\.[0-9A-Za-z-]+)*)?(?:\\+[0-9A-Za-z-]+(?:\\.[0-9A-Za-z-]+)*)?$"
      },
      "digest": {
        "type": "string",
        "pattern": "^sha256:[0-9a-f]{64}$"
      },
      "dateTime": {
        "type": "string",
        "format": "date-time"
      },
      "contractRequirement": {
        "type": "object",
        "required": [
          "id",
          "version"
        ],
        "properties": {
          "id": {
            "type": "string",
            "pattern": "^[A-Za-z][A-Za-z0-9._:-]*$"
          },
          "version": {
            "type": "string",
            "minLength": 1
          },
          "digest": {
            "type": "string",
            "pattern": "^sha256:[0-9a-f]{64}$"
          }
        },
        "patternProperties": {
          "^x-[A-Za-z0-9._:-]+$": true
        },
        "additionalProperties": false
      },
      "exactContractReference": {
        "type": "object",
        "required": [
          "id",
          "version",
          "digest"
        ],
        "properties": {
          "id": {
            "type": "string",
            "pattern": "^[A-Za-z][A-Za-z0-9._:-]*$"
          },
          "version": {
            "type": "string",
            "pattern": "^(0|[1-9][0-9]*)\\.(0|[1-9][0-9]*)\\.(?:0|[1-9][0-9]*)(?:-[0-9A-Za-z-]+(?:\\.[0-9A-Za-z-]+)*)?(?:\\+[0-9A-Za-z-]+(?:\\.[0-9A-Za-z-]+)*)?$"
          },
          "digest": {
            "type": "string",
            "pattern": "^sha256:[0-9a-f]{64}$"
          }
        },
        "patternProperties": {
          "^x-[A-Za-z0-9._:-]+$": true
        },
        "additionalProperties": false
      },
      "identity": {
        "type": "object",
        "required": [
          "application",
          "implementation",
          "version"
        ],
        "properties": {
          "application": {
            "type": "string",
            "pattern": "^[A-Za-z][A-Za-z0-9._:-]*$"
          },
          "implementation": {
            "type": "string",
            "pattern": "^[A-Za-z][A-Za-z0-9._:-]*$"
          },
          "version": {
            "type": "string",
            "pattern": "^(0|[1-9][0-9]*)\\.(0|[1-9][0-9]*)\\.(?:0|[1-9][0-9]*)(?:-[0-9A-Za-z-]+(?:\\.[0-9A-Za-z-]+)*)?(?:\\+[0-9A-Za-z-]+(?:\\.[0-9A-Za-z-]+)*)?$"
          },
          "instance_id": {
            "type": "string",
            "minLength": 1
          }
        },
        "patternProperties": {
          "^x-[A-Za-z0-9._:-]+$": true
        },
        "additionalProperties": false
      },
      "providerSelector": {
        "type": "object",
        "required": [],
        "properties": {
          "application": {
            "type": "string",
            "pattern": "^[A-Za-z][A-Za-z0-9._:-]*$"
          },
          "implementation": {
            "type": "string",
            "pattern": "^[A-Za-z][A-Za-z0-9._:-]*$"
          },
          "instance_id": {
            "type": "string",
            "minLength": 1
          }
        },
        "patternProperties": {
          "^x-[A-Za-z0-9._:-]+$": true
        },
        "additionalProperties": false,
        "minProperties": 1
      },
      "expression": {
        "type": "object",
        "required": [
          "$expr"
        ],
        "properties": {
          "$expr": {
            "type": "string",
            "minLength": 1
          }
        },
        "additionalProperties": false
      }
    },
    "$id": "https://mdbase.dev/schemas/runtime/v0.2/mdbase.runtime.provider-registration/1.0.0.schema.json"
  },
  "runtime_capability_grant": {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "title": "mdbase runtime capability grant",
    "type": "object",
    "required": [
      "type",
      "id",
      "capability",
      "principal",
      "mode",
      "granted_at"
    ],
    "properties": {
      "type": {
        "const": "runtime_capability_grant"
      },
      "id": {
        "type": "string",
        "pattern": "^[A-Za-z][A-Za-z0-9._:-]*$"
      },
      "capability": {
        "type": "string",
        "pattern": "^[A-Za-z][A-Za-z0-9._:-]*$"
      },
      "principal": {
        "$ref": "#/$defs/identity"
      },
      "mode": {
        "enum": [
          "allow",
          "deny"
        ]
      },
      "actions": {
        "type": "array",
        "uniqueItems": true,
        "items": {
          "$ref": "#/$defs/contractRequirement"
        }
      },
      "providers": {
        "type": "array",
        "uniqueItems": true,
        "items": {
          "$ref": "#/$defs/providerSelector"
        }
      },
      "granted_at": {
        "type": "string",
        "format": "date-time"
      },
      "expires_at": {
        "type": "string",
        "format": "date-time"
      }
    },
    "patternProperties": {
      "^x-[A-Za-z0-9._:-]+$": true
    },
    "additionalProperties": false,
    "$defs": {
      "identifier": {
        "type": "string",
        "pattern": "^[A-Za-z][A-Za-z0-9._:-]*$"
      },
      "semanticVersion": {
        "type": "string",
        "pattern": "^(0|[1-9][0-9]*)\\.(0|[1-9][0-9]*)\\.(?:0|[1-9][0-9]*)(?:-[0-9A-Za-z-]+(?:\\.[0-9A-Za-z-]+)*)?(?:\\+[0-9A-Za-z-]+(?:\\.[0-9A-Za-z-]+)*)?$"
      },
      "digest": {
        "type": "string",
        "pattern": "^sha256:[0-9a-f]{64}$"
      },
      "dateTime": {
        "type": "string",
        "format": "date-time"
      },
      "contractRequirement": {
        "type": "object",
        "required": [
          "id",
          "version"
        ],
        "properties": {
          "id": {
            "type": "string",
            "pattern": "^[A-Za-z][A-Za-z0-9._:-]*$"
          },
          "version": {
            "type": "string",
            "minLength": 1
          },
          "digest": {
            "type": "string",
            "pattern": "^sha256:[0-9a-f]{64}$"
          }
        },
        "patternProperties": {
          "^x-[A-Za-z0-9._:-]+$": true
        },
        "additionalProperties": false
      },
      "exactContractReference": {
        "type": "object",
        "required": [
          "id",
          "version",
          "digest"
        ],
        "properties": {
          "id": {
            "type": "string",
            "pattern": "^[A-Za-z][A-Za-z0-9._:-]*$"
          },
          "version": {
            "type": "string",
            "pattern": "^(0|[1-9][0-9]*)\\.(0|[1-9][0-9]*)\\.(?:0|[1-9][0-9]*)(?:-[0-9A-Za-z-]+(?:\\.[0-9A-Za-z-]+)*)?(?:\\+[0-9A-Za-z-]+(?:\\.[0-9A-Za-z-]+)*)?$"
          },
          "digest": {
            "type": "string",
            "pattern": "^sha256:[0-9a-f]{64}$"
          }
        },
        "patternProperties": {
          "^x-[A-Za-z0-9._:-]+$": true
        },
        "additionalProperties": false
      },
      "identity": {
        "type": "object",
        "required": [
          "application",
          "implementation",
          "version"
        ],
        "properties": {
          "application": {
            "type": "string",
            "pattern": "^[A-Za-z][A-Za-z0-9._:-]*$"
          },
          "implementation": {
            "type": "string",
            "pattern": "^[A-Za-z][A-Za-z0-9._:-]*$"
          },
          "version": {
            "type": "string",
            "pattern": "^(0|[1-9][0-9]*)\\.(0|[1-9][0-9]*)\\.(?:0|[1-9][0-9]*)(?:-[0-9A-Za-z-]+(?:\\.[0-9A-Za-z-]+)*)?(?:\\+[0-9A-Za-z-]+(?:\\.[0-9A-Za-z-]+)*)?$"
          },
          "instance_id": {
            "type": "string",
            "minLength": 1
          }
        },
        "patternProperties": {
          "^x-[A-Za-z0-9._:-]+$": true
        },
        "additionalProperties": false
      },
      "providerSelector": {
        "type": "object",
        "required": [],
        "properties": {
          "application": {
            "type": "string",
            "pattern": "^[A-Za-z][A-Za-z0-9._:-]*$"
          },
          "implementation": {
            "type": "string",
            "pattern": "^[A-Za-z][A-Za-z0-9._:-]*$"
          },
          "instance_id": {
            "type": "string",
            "minLength": 1
          }
        },
        "patternProperties": {
          "^x-[A-Za-z0-9._:-]+$": true
        },
        "additionalProperties": false,
        "minProperties": 1
      },
      "expression": {
        "type": "object",
        "required": [
          "$expr"
        ],
        "properties": {
          "$expr": {
            "type": "string",
            "minLength": 1
          }
        },
        "additionalProperties": false
      }
    },
    "$id": "https://mdbase.dev/schemas/runtime/v0.2/mdbase.runtime.capability-grant/1.0.0.schema.json"
  },
  "runtime_run": {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "title": "mdbase durable runtime run",
    "type": "object",
    "required": [
      "type",
      "id",
      "workflow_id",
      "workflow_version",
      "workflow_revision",
      "event_id",
      "event_contract",
      "admitted_plan",
      "status",
      "created_at",
      "updated_at"
    ],
    "properties": {
      "type": {
        "const": "runtime_run"
      },
      "id": {
        "type": "string",
        "pattern": "^[A-Za-z][A-Za-z0-9._:-]*$"
      },
      "workflow_id": {
        "type": "string",
        "pattern": "^[A-Za-z][A-Za-z0-9._:-]*$"
      },
      "workflow_version": {
        "type": "string",
        "pattern": "^(0|[1-9][0-9]*)\\.(0|[1-9][0-9]*)\\.(?:0|[1-9][0-9]*)(?:-[0-9A-Za-z-]+(?:\\.[0-9A-Za-z-]+)*)?(?:\\+[0-9A-Za-z-]+(?:\\.[0-9A-Za-z-]+)*)?$"
      },
      "workflow_revision": {
        "type": "string",
        "pattern": "^sha256:[0-9a-f]{64}$"
      },
      "event_id": {
        "type": "string",
        "minLength": 1
      },
      "event_contract": {
        "$ref": "#/$defs/exactContractReference"
      },
      "event_source": {
        "$ref": "#/$defs/identity"
      },
      "admitted_plan": {
        "$ref": "#/$defs/admittedPlan"
      },
      "policy_id": {
        "type": "string",
        "pattern": "^[A-Za-z][A-Za-z0-9._:-]*$"
      },
      "policy_revision": {
        "type": "string",
        "pattern": "^sha256:[0-9a-f]{64}$"
      },
      "trigger_id": {
        "type": "string",
        "pattern": "^[A-Za-z][A-Za-z0-9._:-]*$"
      },
      "event_cursor": {
        "type": "integer",
        "minimum": 1
      },
      "executor": {
        "type": "string",
        "pattern": "^[A-Za-z][A-Za-z0-9._:-]*$"
      },
      "idempotency_key": {
        "type": "string"
      },
      "concurrency_group": {
        "type": "string"
      },
      "status": {
        "enum": [
          "queued",
          "running",
          "waiting",
          "succeeded",
          "failed",
          "cancelled",
          "indeterminate"
        ]
      },
      "created_at": {
        "type": "string",
        "format": "date-time"
      },
      "updated_at": {
        "type": "string",
        "format": "date-time"
      },
      "started_at": {
        "type": "string",
        "format": "date-time"
      },
      "finished_at": {
        "type": "string",
        "format": "date-time"
      },
      "lease": {
        "$ref": "#/$defs/lease"
      }
    },
    "patternProperties": {
      "^x-[A-Za-z0-9._:-]+$": true
    },
    "additionalProperties": false,
    "$defs": {
      "identifier": {
        "type": "string",
        "pattern": "^[A-Za-z][A-Za-z0-9._:-]*$"
      },
      "semanticVersion": {
        "type": "string",
        "pattern": "^(0|[1-9][0-9]*)\\.(0|[1-9][0-9]*)\\.(?:0|[1-9][0-9]*)(?:-[0-9A-Za-z-]+(?:\\.[0-9A-Za-z-]+)*)?(?:\\+[0-9A-Za-z-]+(?:\\.[0-9A-Za-z-]+)*)?$"
      },
      "digest": {
        "type": "string",
        "pattern": "^sha256:[0-9a-f]{64}$"
      },
      "dateTime": {
        "type": "string",
        "format": "date-time"
      },
      "contractRequirement": {
        "type": "object",
        "required": [
          "id",
          "version"
        ],
        "properties": {
          "id": {
            "type": "string",
            "pattern": "^[A-Za-z][A-Za-z0-9._:-]*$"
          },
          "version": {
            "type": "string",
            "minLength": 1
          },
          "digest": {
            "type": "string",
            "pattern": "^sha256:[0-9a-f]{64}$"
          }
        },
        "patternProperties": {
          "^x-[A-Za-z0-9._:-]+$": true
        },
        "additionalProperties": false
      },
      "exactContractReference": {
        "type": "object",
        "required": [
          "id",
          "version",
          "digest"
        ],
        "properties": {
          "id": {
            "type": "string",
            "pattern": "^[A-Za-z][A-Za-z0-9._:-]*$"
          },
          "version": {
            "type": "string",
            "pattern": "^(0|[1-9][0-9]*)\\.(0|[1-9][0-9]*)\\.(?:0|[1-9][0-9]*)(?:-[0-9A-Za-z-]+(?:\\.[0-9A-Za-z-]+)*)?(?:\\+[0-9A-Za-z-]+(?:\\.[0-9A-Za-z-]+)*)?$"
          },
          "digest": {
            "type": "string",
            "pattern": "^sha256:[0-9a-f]{64}$"
          }
        },
        "patternProperties": {
          "^x-[A-Za-z0-9._:-]+$": true
        },
        "additionalProperties": false
      },
      "identity": {
        "type": "object",
        "required": [
          "application",
          "implementation",
          "version"
        ],
        "properties": {
          "application": {
            "type": "string",
            "pattern": "^[A-Za-z][A-Za-z0-9._:-]*$"
          },
          "implementation": {
            "type": "string",
            "pattern": "^[A-Za-z][A-Za-z0-9._:-]*$"
          },
          "version": {
            "type": "string",
            "pattern": "^(0|[1-9][0-9]*)\\.(0|[1-9][0-9]*)\\.(?:0|[1-9][0-9]*)(?:-[0-9A-Za-z-]+(?:\\.[0-9A-Za-z-]+)*)?(?:\\+[0-9A-Za-z-]+(?:\\.[0-9A-Za-z-]+)*)?$"
          },
          "instance_id": {
            "type": "string",
            "minLength": 1
          }
        },
        "patternProperties": {
          "^x-[A-Za-z0-9._:-]+$": true
        },
        "additionalProperties": false
      },
      "providerSelector": {
        "type": "object",
        "required": [],
        "properties": {
          "application": {
            "type": "string",
            "pattern": "^[A-Za-z][A-Za-z0-9._:-]*$"
          },
          "implementation": {
            "type": "string",
            "pattern": "^[A-Za-z][A-Za-z0-9._:-]*$"
          },
          "instance_id": {
            "type": "string",
            "minLength": 1
          }
        },
        "patternProperties": {
          "^x-[A-Za-z0-9._:-]+$": true
        },
        "additionalProperties": false,
        "minProperties": 1
      },
      "expression": {
        "type": "object",
        "required": [
          "$expr"
        ],
        "properties": {
          "$expr": {
            "type": "string",
            "minLength": 1
          }
        },
        "additionalProperties": false
      },
      "admittedPlan": {
        "type": "object",
        "required": [
          "profile_version",
          "workflow_revision",
          "event",
          "steps"
        ],
        "properties": {
          "profile_version": {
            "const": "0.2"
          },
          "workflow_revision": {
            "type": "string",
            "pattern": "^sha256:[0-9a-f]{64}$"
          },
          "event": {
            "type": "object",
            "required": [
              "contract",
              "source"
            ],
            "properties": {
              "contract": {
                "$ref": "#/$defs/exactContractReference"
              },
              "source": {
                "$ref": "#/$defs/identity"
              },
              "source_declaration_digest": {
                "type": "string",
                "pattern": "^sha256:[0-9a-f]{64}$"
              }
            },
            "patternProperties": {
              "^x-[A-Za-z0-9._:-]+$": true
            },
            "additionalProperties": false
          },
          "steps": {
            "type": "array",
            "items": {
              "type": "object",
              "required": [
                "id",
                "contract",
                "provider",
                "provider_declaration_digest",
                "handler_id"
              ],
              "properties": {
                "id": {
                  "type": "string",
                  "pattern": "^[A-Za-z][A-Za-z0-9._:-]*$"
                },
                "contract": {
                  "$ref": "#/$defs/exactContractReference"
                },
                "provider": {
                  "$ref": "#/$defs/identity"
                },
                "provider_declaration_digest": {
                  "type": "string",
                  "pattern": "^sha256:[0-9a-f]{64}$"
                },
                "handler_id": {
                  "type": "string",
                  "pattern": "^[A-Za-z][A-Za-z0-9._:-]*$"
                }
              },
              "patternProperties": {
                "^x-[A-Za-z0-9._:-]+$": true
              },
              "additionalProperties": false
            }
          }
        },
        "patternProperties": {
          "^x-[A-Za-z0-9._:-]+$": true
        },
        "additionalProperties": false
      },
      "lease": {
        "type": "object",
        "required": [
          "owner",
          "token",
          "expires_at"
        ],
        "properties": {
          "owner": {
            "type": "string",
            "pattern": "^[A-Za-z][A-Za-z0-9._:-]*$"
          },
          "token": {
            "type": "string",
            "minLength": 1
          },
          "expires_at": {
            "type": "string",
            "format": "date-time"
          }
        },
        "patternProperties": {
          "^x-[A-Za-z0-9._:-]+$": true
        },
        "additionalProperties": false
      }
    },
    "$id": "https://mdbase.dev/schemas/runtime/v0.2/mdbase.runtime.run/1.0.0.schema.json"
  },
  "runtime_action_attempt": {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "title": "mdbase durable runtime action attempt",
    "type": "object",
    "required": [
      "type",
      "id",
      "run_id",
      "step_id",
      "request_id",
      "invocation_id",
      "attempt_id",
      "contract",
      "provider",
      "provider_declaration_digest",
      "status",
      "created_at",
      "updated_at"
    ],
    "properties": {
      "type": {
        "const": "runtime_action_attempt"
      },
      "id": {
        "type": "string",
        "pattern": "^[A-Za-z][A-Za-z0-9._:-]*$"
      },
      "run_id": {
        "type": "string",
        "pattern": "^[A-Za-z][A-Za-z0-9._:-]*$"
      },
      "step_id": {
        "type": "string",
        "pattern": "^[A-Za-z][A-Za-z0-9._:-]*$"
      },
      "request_id": {
        "type": "string",
        "minLength": 1
      },
      "invocation_id": {
        "type": "string",
        "minLength": 1
      },
      "attempt_id": {
        "type": "string",
        "minLength": 1
      },
      "contract": {
        "$ref": "#/$defs/exactContractReference"
      },
      "provider": {
        "$ref": "#/$defs/identity"
      },
      "provider_declaration_digest": {
        "type": "string",
        "pattern": "^sha256:[0-9a-f]{64}$"
      },
      "handler_id": {
        "type": "string",
        "pattern": "^[A-Za-z][A-Za-z0-9._:-]*$"
      },
      "idempotency_key": {
        "type": "string"
      },
      "status": {
        "enum": [
          "admitted",
          "dispatching",
          "succeeded",
          "rejected",
          "failed",
          "cancelled",
          "indeterminate"
        ]
      },
      "request": {
        "type": "object"
      },
      "invocation": {
        "type": "object"
      },
      "outcome": {
        "type": "object"
      },
      "created_at": {
        "type": "string",
        "format": "date-time"
      },
      "updated_at": {
        "type": "string",
        "format": "date-time"
      },
      "completed_at": {
        "type": "string",
        "format": "date-time"
      }
    },
    "patternProperties": {
      "^x-[A-Za-z0-9._:-]+$": true
    },
    "additionalProperties": false,
    "$defs": {
      "identifier": {
        "type": "string",
        "pattern": "^[A-Za-z][A-Za-z0-9._:-]*$"
      },
      "semanticVersion": {
        "type": "string",
        "pattern": "^(0|[1-9][0-9]*)\\.(0|[1-9][0-9]*)\\.(?:0|[1-9][0-9]*)(?:-[0-9A-Za-z-]+(?:\\.[0-9A-Za-z-]+)*)?(?:\\+[0-9A-Za-z-]+(?:\\.[0-9A-Za-z-]+)*)?$"
      },
      "digest": {
        "type": "string",
        "pattern": "^sha256:[0-9a-f]{64}$"
      },
      "dateTime": {
        "type": "string",
        "format": "date-time"
      },
      "contractRequirement": {
        "type": "object",
        "required": [
          "id",
          "version"
        ],
        "properties": {
          "id": {
            "type": "string",
            "pattern": "^[A-Za-z][A-Za-z0-9._:-]*$"
          },
          "version": {
            "type": "string",
            "minLength": 1
          },
          "digest": {
            "type": "string",
            "pattern": "^sha256:[0-9a-f]{64}$"
          }
        },
        "patternProperties": {
          "^x-[A-Za-z0-9._:-]+$": true
        },
        "additionalProperties": false
      },
      "exactContractReference": {
        "type": "object",
        "required": [
          "id",
          "version",
          "digest"
        ],
        "properties": {
          "id": {
            "type": "string",
            "pattern": "^[A-Za-z][A-Za-z0-9._:-]*$"
          },
          "version": {
            "type": "string",
            "pattern": "^(0|[1-9][0-9]*)\\.(0|[1-9][0-9]*)\\.(?:0|[1-9][0-9]*)(?:-[0-9A-Za-z-]+(?:\\.[0-9A-Za-z-]+)*)?(?:\\+[0-9A-Za-z-]+(?:\\.[0-9A-Za-z-]+)*)?$"
          },
          "digest": {
            "type": "string",
            "pattern": "^sha256:[0-9a-f]{64}$"
          }
        },
        "patternProperties": {
          "^x-[A-Za-z0-9._:-]+$": true
        },
        "additionalProperties": false
      },
      "identity": {
        "type": "object",
        "required": [
          "application",
          "implementation",
          "version"
        ],
        "properties": {
          "application": {
            "type": "string",
            "pattern": "^[A-Za-z][A-Za-z0-9._:-]*$"
          },
          "implementation": {
            "type": "string",
            "pattern": "^[A-Za-z][A-Za-z0-9._:-]*$"
          },
          "version": {
            "type": "string",
            "pattern": "^(0|[1-9][0-9]*)\\.(0|[1-9][0-9]*)\\.(?:0|[1-9][0-9]*)(?:-[0-9A-Za-z-]+(?:\\.[0-9A-Za-z-]+)*)?(?:\\+[0-9A-Za-z-]+(?:\\.[0-9A-Za-z-]+)*)?$"
          },
          "instance_id": {
            "type": "string",
            "minLength": 1
          }
        },
        "patternProperties": {
          "^x-[A-Za-z0-9._:-]+$": true
        },
        "additionalProperties": false
      },
      "providerSelector": {
        "type": "object",
        "required": [],
        "properties": {
          "application": {
            "type": "string",
            "pattern": "^[A-Za-z][A-Za-z0-9._:-]*$"
          },
          "implementation": {
            "type": "string",
            "pattern": "^[A-Za-z][A-Za-z0-9._:-]*$"
          },
          "instance_id": {
            "type": "string",
            "minLength": 1
          }
        },
        "patternProperties": {
          "^x-[A-Za-z0-9._:-]+$": true
        },
        "additionalProperties": false,
        "minProperties": 1
      },
      "expression": {
        "type": "object",
        "required": [
          "$expr"
        ],
        "properties": {
          "$expr": {
            "type": "string",
            "minLength": 1
          }
        },
        "additionalProperties": false
      }
    },
    "$id": "https://mdbase.dev/schemas/runtime/v0.2/mdbase.runtime.action-attempt/1.0.0.schema.json"
  },
  "runtime_checkpoint": {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "title": "mdbase durable runtime checkpoint",
    "type": "object",
    "required": [
      "type",
      "id",
      "run_id",
      "generation",
      "status",
      "state",
      "updated_at"
    ],
    "properties": {
      "type": {
        "const": "runtime_checkpoint"
      },
      "id": {
        "type": "string",
        "pattern": "^[A-Za-z][A-Za-z0-9._:-]*$"
      },
      "run_id": {
        "type": "string",
        "pattern": "^[A-Za-z][A-Za-z0-9._:-]*$"
      },
      "generation": {
        "type": "integer",
        "minimum": 1
      },
      "status": {
        "enum": [
          "open",
          "waiting",
          "ready",
          "completed",
          "failed",
          "cancelled"
        ]
      },
      "state": {
        "type": "object"
      },
      "updated_at": {
        "type": "string",
        "format": "date-time"
      }
    },
    "patternProperties": {
      "^x-[A-Za-z0-9._:-]+$": true
    },
    "additionalProperties": false,
    "$defs": {
      "identifier": {
        "type": "string",
        "pattern": "^[A-Za-z][A-Za-z0-9._:-]*$"
      },
      "semanticVersion": {
        "type": "string",
        "pattern": "^(0|[1-9][0-9]*)\\.(0|[1-9][0-9]*)\\.(?:0|[1-9][0-9]*)(?:-[0-9A-Za-z-]+(?:\\.[0-9A-Za-z-]+)*)?(?:\\+[0-9A-Za-z-]+(?:\\.[0-9A-Za-z-]+)*)?$"
      },
      "digest": {
        "type": "string",
        "pattern": "^sha256:[0-9a-f]{64}$"
      },
      "dateTime": {
        "type": "string",
        "format": "date-time"
      },
      "contractRequirement": {
        "type": "object",
        "required": [
          "id",
          "version"
        ],
        "properties": {
          "id": {
            "type": "string",
            "pattern": "^[A-Za-z][A-Za-z0-9._:-]*$"
          },
          "version": {
            "type": "string",
            "minLength": 1
          },
          "digest": {
            "type": "string",
            "pattern": "^sha256:[0-9a-f]{64}$"
          }
        },
        "patternProperties": {
          "^x-[A-Za-z0-9._:-]+$": true
        },
        "additionalProperties": false
      },
      "exactContractReference": {
        "type": "object",
        "required": [
          "id",
          "version",
          "digest"
        ],
        "properties": {
          "id": {
            "type": "string",
            "pattern": "^[A-Za-z][A-Za-z0-9._:-]*$"
          },
          "version": {
            "type": "string",
            "pattern": "^(0|[1-9][0-9]*)\\.(0|[1-9][0-9]*)\\.(?:0|[1-9][0-9]*)(?:-[0-9A-Za-z-]+(?:\\.[0-9A-Za-z-]+)*)?(?:\\+[0-9A-Za-z-]+(?:\\.[0-9A-Za-z-]+)*)?$"
          },
          "digest": {
            "type": "string",
            "pattern": "^sha256:[0-9a-f]{64}$"
          }
        },
        "patternProperties": {
          "^x-[A-Za-z0-9._:-]+$": true
        },
        "additionalProperties": false
      },
      "identity": {
        "type": "object",
        "required": [
          "application",
          "implementation",
          "version"
        ],
        "properties": {
          "application": {
            "type": "string",
            "pattern": "^[A-Za-z][A-Za-z0-9._:-]*$"
          },
          "implementation": {
            "type": "string",
            "pattern": "^[A-Za-z][A-Za-z0-9._:-]*$"
          },
          "version": {
            "type": "string",
            "pattern": "^(0|[1-9][0-9]*)\\.(0|[1-9][0-9]*)\\.(?:0|[1-9][0-9]*)(?:-[0-9A-Za-z-]+(?:\\.[0-9A-Za-z-]+)*)?(?:\\+[0-9A-Za-z-]+(?:\\.[0-9A-Za-z-]+)*)?$"
          },
          "instance_id": {
            "type": "string",
            "minLength": 1
          }
        },
        "patternProperties": {
          "^x-[A-Za-z0-9._:-]+$": true
        },
        "additionalProperties": false
      },
      "providerSelector": {
        "type": "object",
        "required": [],
        "properties": {
          "application": {
            "type": "string",
            "pattern": "^[A-Za-z][A-Za-z0-9._:-]*$"
          },
          "implementation": {
            "type": "string",
            "pattern": "^[A-Za-z][A-Za-z0-9._:-]*$"
          },
          "instance_id": {
            "type": "string",
            "minLength": 1
          }
        },
        "patternProperties": {
          "^x-[A-Za-z0-9._:-]+$": true
        },
        "additionalProperties": false,
        "minProperties": 1
      },
      "expression": {
        "type": "object",
        "required": [
          "$expr"
        ],
        "properties": {
          "$expr": {
            "type": "string",
            "minLength": 1
          }
        },
        "additionalProperties": false
      }
    },
    "$id": "https://mdbase.dev/schemas/runtime/v0.2/mdbase.runtime.checkpoint/1.0.0.schema.json"
  },
  "runtime_timer": {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "title": "mdbase durable runtime timer",
    "type": "object",
    "required": [
      "type",
      "id",
      "generation",
      "status",
      "fire_at",
      "event",
      "created_at",
      "updated_at"
    ],
    "properties": {
      "type": {
        "const": "runtime_timer"
      },
      "id": {
        "type": "string",
        "pattern": "^[A-Za-z][A-Za-z0-9._:-]*$"
      },
      "generation": {
        "type": "integer",
        "minimum": 1
      },
      "status": {
        "enum": [
          "scheduled",
          "firing",
          "fired",
          "cancelled"
        ]
      },
      "fire_at": {
        "type": "string",
        "format": "date-time"
      },
      "event": {
        "type": "object",
        "required": [
          "contract",
          "data"
        ],
        "properties": {
          "contract": {
            "$ref": "#/$defs/contractRequirement"
          },
          "subject": {
            "type": "string"
          },
          "correlation_id": {
            "type": "string"
          },
          "causation_id": {
            "type": "string"
          },
          "data": {}
        },
        "patternProperties": {
          "^x-[A-Za-z0-9._:-]+$": true
        },
        "additionalProperties": false
      },
      "missed_run_policy": {
        "const": "fire_once"
      },
      "created_at": {
        "type": "string",
        "format": "date-time"
      },
      "updated_at": {
        "type": "string",
        "format": "date-time"
      },
      "fired_at": {
        "type": "string",
        "format": "date-time"
      }
    },
    "patternProperties": {
      "^x-[A-Za-z0-9._:-]+$": true
    },
    "additionalProperties": false,
    "$defs": {
      "identifier": {
        "type": "string",
        "pattern": "^[A-Za-z][A-Za-z0-9._:-]*$"
      },
      "semanticVersion": {
        "type": "string",
        "pattern": "^(0|[1-9][0-9]*)\\.(0|[1-9][0-9]*)\\.(?:0|[1-9][0-9]*)(?:-[0-9A-Za-z-]+(?:\\.[0-9A-Za-z-]+)*)?(?:\\+[0-9A-Za-z-]+(?:\\.[0-9A-Za-z-]+)*)?$"
      },
      "digest": {
        "type": "string",
        "pattern": "^sha256:[0-9a-f]{64}$"
      },
      "dateTime": {
        "type": "string",
        "format": "date-time"
      },
      "contractRequirement": {
        "type": "object",
        "required": [
          "id",
          "version"
        ],
        "properties": {
          "id": {
            "type": "string",
            "pattern": "^[A-Za-z][A-Za-z0-9._:-]*$"
          },
          "version": {
            "type": "string",
            "minLength": 1
          },
          "digest": {
            "type": "string",
            "pattern": "^sha256:[0-9a-f]{64}$"
          }
        },
        "patternProperties": {
          "^x-[A-Za-z0-9._:-]+$": true
        },
        "additionalProperties": false
      },
      "exactContractReference": {
        "type": "object",
        "required": [
          "id",
          "version",
          "digest"
        ],
        "properties": {
          "id": {
            "type": "string",
            "pattern": "^[A-Za-z][A-Za-z0-9._:-]*$"
          },
          "version": {
            "type": "string",
            "pattern": "^(0|[1-9][0-9]*)\\.(0|[1-9][0-9]*)\\.(?:0|[1-9][0-9]*)(?:-[0-9A-Za-z-]+(?:\\.[0-9A-Za-z-]+)*)?(?:\\+[0-9A-Za-z-]+(?:\\.[0-9A-Za-z-]+)*)?$"
          },
          "digest": {
            "type": "string",
            "pattern": "^sha256:[0-9a-f]{64}$"
          }
        },
        "patternProperties": {
          "^x-[A-Za-z0-9._:-]+$": true
        },
        "additionalProperties": false
      },
      "identity": {
        "type": "object",
        "required": [
          "application",
          "implementation",
          "version"
        ],
        "properties": {
          "application": {
            "type": "string",
            "pattern": "^[A-Za-z][A-Za-z0-9._:-]*$"
          },
          "implementation": {
            "type": "string",
            "pattern": "^[A-Za-z][A-Za-z0-9._:-]*$"
          },
          "version": {
            "type": "string",
            "pattern": "^(0|[1-9][0-9]*)\\.(0|[1-9][0-9]*)\\.(?:0|[1-9][0-9]*)(?:-[0-9A-Za-z-]+(?:\\.[0-9A-Za-z-]+)*)?(?:\\+[0-9A-Za-z-]+(?:\\.[0-9A-Za-z-]+)*)?$"
          },
          "instance_id": {
            "type": "string",
            "minLength": 1
          }
        },
        "patternProperties": {
          "^x-[A-Za-z0-9._:-]+$": true
        },
        "additionalProperties": false
      },
      "providerSelector": {
        "type": "object",
        "required": [],
        "properties": {
          "application": {
            "type": "string",
            "pattern": "^[A-Za-z][A-Za-z0-9._:-]*$"
          },
          "implementation": {
            "type": "string",
            "pattern": "^[A-Za-z][A-Za-z0-9._:-]*$"
          },
          "instance_id": {
            "type": "string",
            "minLength": 1
          }
        },
        "patternProperties": {
          "^x-[A-Za-z0-9._:-]+$": true
        },
        "additionalProperties": false,
        "minProperties": 1
      },
      "expression": {
        "type": "object",
        "required": [
          "$expr"
        ],
        "properties": {
          "$expr": {
            "type": "string",
            "minLength": 1
          }
        },
        "additionalProperties": false
      }
    },
    "$id": "https://mdbase.dev/schemas/runtime/v0.2/mdbase.runtime.timer/1.0.0.schema.json"
  },
  "runtime_diagnostic": {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "title": "mdbase durable runtime diagnostic",
    "type": "object",
    "required": [
      "type",
      "id",
      "severity",
      "code",
      "message",
      "created_at"
    ],
    "properties": {
      "type": {
        "const": "runtime_diagnostic"
      },
      "id": {
        "type": "string",
        "pattern": "^[A-Za-z][A-Za-z0-9._:-]*$"
      },
      "severity": {
        "enum": [
          "info",
          "warning",
          "error"
        ]
      },
      "code": {
        "type": "string",
        "pattern": "^[A-Za-z][A-Za-z0-9._:-]*$"
      },
      "message": {
        "type": "string",
        "minLength": 1
      },
      "run_id": {
        "type": "string",
        "pattern": "^[A-Za-z][A-Za-z0-9._:-]*$"
      },
      "attempt_id": {
        "type": "string",
        "pattern": "^[A-Za-z][A-Za-z0-9._:-]*$"
      },
      "path": {
        "type": "string"
      },
      "details": {},
      "created_at": {
        "type": "string",
        "format": "date-time"
      }
    },
    "patternProperties": {
      "^x-[A-Za-z0-9._:-]+$": true
    },
    "additionalProperties": false,
    "$defs": {
      "identifier": {
        "type": "string",
        "pattern": "^[A-Za-z][A-Za-z0-9._:-]*$"
      },
      "semanticVersion": {
        "type": "string",
        "pattern": "^(0|[1-9][0-9]*)\\.(0|[1-9][0-9]*)\\.(?:0|[1-9][0-9]*)(?:-[0-9A-Za-z-]+(?:\\.[0-9A-Za-z-]+)*)?(?:\\+[0-9A-Za-z-]+(?:\\.[0-9A-Za-z-]+)*)?$"
      },
      "digest": {
        "type": "string",
        "pattern": "^sha256:[0-9a-f]{64}$"
      },
      "dateTime": {
        "type": "string",
        "format": "date-time"
      },
      "contractRequirement": {
        "type": "object",
        "required": [
          "id",
          "version"
        ],
        "properties": {
          "id": {
            "type": "string",
            "pattern": "^[A-Za-z][A-Za-z0-9._:-]*$"
          },
          "version": {
            "type": "string",
            "minLength": 1
          },
          "digest": {
            "type": "string",
            "pattern": "^sha256:[0-9a-f]{64}$"
          }
        },
        "patternProperties": {
          "^x-[A-Za-z0-9._:-]+$": true
        },
        "additionalProperties": false
      },
      "exactContractReference": {
        "type": "object",
        "required": [
          "id",
          "version",
          "digest"
        ],
        "properties": {
          "id": {
            "type": "string",
            "pattern": "^[A-Za-z][A-Za-z0-9._:-]*$"
          },
          "version": {
            "type": "string",
            "pattern": "^(0|[1-9][0-9]*)\\.(0|[1-9][0-9]*)\\.(?:0|[1-9][0-9]*)(?:-[0-9A-Za-z-]+(?:\\.[0-9A-Za-z-]+)*)?(?:\\+[0-9A-Za-z-]+(?:\\.[0-9A-Za-z-]+)*)?$"
          },
          "digest": {
            "type": "string",
            "pattern": "^sha256:[0-9a-f]{64}$"
          }
        },
        "patternProperties": {
          "^x-[A-Za-z0-9._:-]+$": true
        },
        "additionalProperties": false
      },
      "identity": {
        "type": "object",
        "required": [
          "application",
          "implementation",
          "version"
        ],
        "properties": {
          "application": {
            "type": "string",
            "pattern": "^[A-Za-z][A-Za-z0-9._:-]*$"
          },
          "implementation": {
            "type": "string",
            "pattern": "^[A-Za-z][A-Za-z0-9._:-]*$"
          },
          "version": {
            "type": "string",
            "pattern": "^(0|[1-9][0-9]*)\\.(0|[1-9][0-9]*)\\.(?:0|[1-9][0-9]*)(?:-[0-9A-Za-z-]+(?:\\.[0-9A-Za-z-]+)*)?(?:\\+[0-9A-Za-z-]+(?:\\.[0-9A-Za-z-]+)*)?$"
          },
          "instance_id": {
            "type": "string",
            "minLength": 1
          }
        },
        "patternProperties": {
          "^x-[A-Za-z0-9._:-]+$": true
        },
        "additionalProperties": false
      },
      "providerSelector": {
        "type": "object",
        "required": [],
        "properties": {
          "application": {
            "type": "string",
            "pattern": "^[A-Za-z][A-Za-z0-9._:-]*$"
          },
          "implementation": {
            "type": "string",
            "pattern": "^[A-Za-z][A-Za-z0-9._:-]*$"
          },
          "instance_id": {
            "type": "string",
            "minLength": 1
          }
        },
        "patternProperties": {
          "^x-[A-Za-z0-9._:-]+$": true
        },
        "additionalProperties": false,
        "minProperties": 1
      },
      "expression": {
        "type": "object",
        "required": [
          "$expr"
        ],
        "properties": {
          "$expr": {
            "type": "string",
            "minLength": 1
          }
        },
        "additionalProperties": false
      }
    },
    "$id": "https://mdbase.dev/schemas/runtime/v0.2/mdbase.runtime.diagnostic/1.0.0.schema.json"
  },
  "runtime_dead_letter": {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "title": "mdbase durable runtime dead letter",
    "type": "object",
    "required": [
      "type",
      "id",
      "reason",
      "status",
      "evidence",
      "created_at"
    ],
    "properties": {
      "type": {
        "const": "runtime_dead_letter"
      },
      "id": {
        "type": "string",
        "pattern": "^[A-Za-z][A-Za-z0-9._:-]*$"
      },
      "reason": {
        "type": "string",
        "pattern": "^[A-Za-z][A-Za-z0-9._:-]*$"
      },
      "status": {
        "enum": [
          "unresolved",
          "acknowledged",
          "requeued"
        ]
      },
      "evidence_kind": {
        "enum": [
          "event",
          "action_request",
          "action_outcome"
        ]
      },
      "evidence": {
        "type": "object"
      },
      "created_at": {
        "type": "string",
        "format": "date-time"
      },
      "acknowledged_at": {
        "type": "string",
        "format": "date-time"
      }
    },
    "patternProperties": {
      "^x-[A-Za-z0-9._:-]+$": true
    },
    "additionalProperties": false,
    "$defs": {
      "identifier": {
        "type": "string",
        "pattern": "^[A-Za-z][A-Za-z0-9._:-]*$"
      },
      "semanticVersion": {
        "type": "string",
        "pattern": "^(0|[1-9][0-9]*)\\.(0|[1-9][0-9]*)\\.(?:0|[1-9][0-9]*)(?:-[0-9A-Za-z-]+(?:\\.[0-9A-Za-z-]+)*)?(?:\\+[0-9A-Za-z-]+(?:\\.[0-9A-Za-z-]+)*)?$"
      },
      "digest": {
        "type": "string",
        "pattern": "^sha256:[0-9a-f]{64}$"
      },
      "dateTime": {
        "type": "string",
        "format": "date-time"
      },
      "contractRequirement": {
        "type": "object",
        "required": [
          "id",
          "version"
        ],
        "properties": {
          "id": {
            "type": "string",
            "pattern": "^[A-Za-z][A-Za-z0-9._:-]*$"
          },
          "version": {
            "type": "string",
            "minLength": 1
          },
          "digest": {
            "type": "string",
            "pattern": "^sha256:[0-9a-f]{64}$"
          }
        },
        "patternProperties": {
          "^x-[A-Za-z0-9._:-]+$": true
        },
        "additionalProperties": false
      },
      "exactContractReference": {
        "type": "object",
        "required": [
          "id",
          "version",
          "digest"
        ],
        "properties": {
          "id": {
            "type": "string",
            "pattern": "^[A-Za-z][A-Za-z0-9._:-]*$"
          },
          "version": {
            "type": "string",
            "pattern": "^(0|[1-9][0-9]*)\\.(0|[1-9][0-9]*)\\.(?:0|[1-9][0-9]*)(?:-[0-9A-Za-z-]+(?:\\.[0-9A-Za-z-]+)*)?(?:\\+[0-9A-Za-z-]+(?:\\.[0-9A-Za-z-]+)*)?$"
          },
          "digest": {
            "type": "string",
            "pattern": "^sha256:[0-9a-f]{64}$"
          }
        },
        "patternProperties": {
          "^x-[A-Za-z0-9._:-]+$": true
        },
        "additionalProperties": false
      },
      "identity": {
        "type": "object",
        "required": [
          "application",
          "implementation",
          "version"
        ],
        "properties": {
          "application": {
            "type": "string",
            "pattern": "^[A-Za-z][A-Za-z0-9._:-]*$"
          },
          "implementation": {
            "type": "string",
            "pattern": "^[A-Za-z][A-Za-z0-9._:-]*$"
          },
          "version": {
            "type": "string",
            "pattern": "^(0|[1-9][0-9]*)\\.(0|[1-9][0-9]*)\\.(?:0|[1-9][0-9]*)(?:-[0-9A-Za-z-]+(?:\\.[0-9A-Za-z-]+)*)?(?:\\+[0-9A-Za-z-]+(?:\\.[0-9A-Za-z-]+)*)?$"
          },
          "instance_id": {
            "type": "string",
            "minLength": 1
          }
        },
        "patternProperties": {
          "^x-[A-Za-z0-9._:-]+$": true
        },
        "additionalProperties": false
      },
      "providerSelector": {
        "type": "object",
        "required": [],
        "properties": {
          "application": {
            "type": "string",
            "pattern": "^[A-Za-z][A-Za-z0-9._:-]*$"
          },
          "implementation": {
            "type": "string",
            "pattern": "^[A-Za-z][A-Za-z0-9._:-]*$"
          },
          "instance_id": {
            "type": "string",
            "minLength": 1
          }
        },
        "patternProperties": {
          "^x-[A-Za-z0-9._:-]+$": true
        },
        "additionalProperties": false,
        "minProperties": 1
      },
      "expression": {
        "type": "object",
        "required": [
          "$expr"
        ],
        "properties": {
          "$expr": {
            "type": "string",
            "minLength": 1
          }
        },
        "additionalProperties": false
      }
    },
    "$id": "https://mdbase.dev/schemas/runtime/v0.2/mdbase.runtime.dead-letter/1.0.0.schema.json"
  }
};
