// Generated by scripts/generate-schema-module.mjs. Do not edit directly.

export const GENERATED_CANONICAL_SCHEMAS: Record<string, Record<string, unknown>> = {
  "config": {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://mdbase.dev/schemas/v0.3/config.schema.json",
    "title": "mdbase v0.3 collection configuration",
    "type": "object",
    "required": [
      "spec_version"
    ],
    "properties": {
      "spec_version": {
        "const": "0.3.0"
      },
      "settings": {
        "$ref": "#/$defs/settings"
      },
      "runtime": {
        "$ref": "#/$defs/runtime"
      }
    },
    "patternProperties": {
      "^x-[A-Za-z][A-Za-z0-9._:-]{0,127}$": true
    },
    "additionalProperties": true,
    "$defs": {
      "settings": {
        "type": "object",
        "properties": {
          "types_folder": {
            "type": "string",
            "minLength": 1
          },
          "contracts_folder": {
            "type": "string",
            "minLength": 1
          },
          "record_extensions": {
            "type": "array",
            "minItems": 1,
            "uniqueItems": true,
            "items": {
              "type": "string",
              "pattern": "^[A-Za-z0-9]+$"
            }
          },
          "validation": {
            "enum": [
              "off",
              "warn",
              "error"
            ]
          },
          "explicit_type_keys": {
            "type": "array",
            "uniqueItems": true,
            "items": {
              "type": "string",
              "minLength": 1
            }
          },
          "id_field": {
            "type": "string",
            "minLength": 1
          },
          "include_subfolders": {
            "type": "boolean"
          },
          "exclude": {
            "type": "array",
            "items": {
              "type": "string",
              "minLength": 1
            }
          }
        },
        "additionalProperties": true
      },
      "runtime": {
        "type": "object",
        "required": [
          "profile_version"
        ],
        "properties": {
          "profile_version": {
            "const": "0.1.0"
          },
          "enabled": {
            "type": "boolean"
          },
          "contract_mode": {
            "enum": [
              "runtime",
              "materialized",
              "strict"
            ]
          },
          "policy": {
            "type": "string",
            "minLength": 1
          },
          "materialize": {
            "type": "object",
            "additionalProperties": true
          }
        },
        "additionalProperties": true
      }
    }
  },
  "conformanceClaim": {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://mdbase.dev/schemas/v0.3/conformance-claim.schema.json",
    "title": "mdbase v0.3 conformance claim",
    "type": "object",
    "required": [
      "kind",
      "status",
      "implementation",
      "spec_version",
      "profiles",
      "json_schema",
      "limits",
      "evidence"
    ],
    "properties": {
      "kind": {
        "const": "mdbase.conformance"
      },
      "status": {
        "const": "verified"
      },
      "implementation": {
        "type": "object",
        "required": [
          "id",
          "name",
          "version"
        ],
        "properties": {
          "id": {
            "$ref": "#/$defs/identifier"
          },
          "name": {
            "type": "string",
            "minLength": 1
          },
          "version": {
            "type": "string",
            "minLength": 1
          },
          "language": {
            "type": "string",
            "minLength": 1
          },
          "target": {
            "type": "string",
            "minLength": 1
          },
          "url": {
            "type": "string",
            "format": "uri"
          }
        },
        "patternProperties": {
          "^x-[A-Za-z0-9._:-]+$": true
        },
        "additionalProperties": false
      },
      "spec_version": {
        "type": "string",
        "pattern": "^0\\.3\\.0(?:-[0-9A-Za-z-]+(?:\\.[0-9A-Za-z-]+)*)?$"
      },
      "runtime_profile_version": {
        "const": "0.1.0"
      },
      "profiles": {
        "type": "array",
        "minItems": 1,
        "uniqueItems": true,
        "items": {
          "$ref": "#/$defs/profile"
        }
      },
      "optional_features": {
        "type": "array",
        "uniqueItems": true,
        "items": {
          "$ref": "#/$defs/identifier"
        }
      },
      "json_schema": {
        "type": "object",
        "required": [
          "dialect",
          "keywords",
          "formats",
          "remote_refs"
        ],
        "properties": {
          "dialect": {
            "const": "https://json-schema.org/draft/2020-12/schema"
          },
          "keywords": {
            "type": "array",
            "uniqueItems": true,
            "items": {
              "type": "string",
              "minLength": 1
            }
          },
          "formats": {
            "type": "array",
            "uniqueItems": true,
            "items": {
              "type": "string",
              "minLength": 1
            }
          },
          "remote_refs": {
            "const": false
          }
        },
        "additionalProperties": false
      },
      "compatibility": {
        "type": "object",
        "properties": {
          "v0_2_read": {
            "type": "boolean"
          },
          "v0_2_migrate": {
            "type": "boolean"
          }
        },
        "additionalProperties": false
      },
      "limits": {
        "type": "object",
        "additionalProperties": {
          "$ref": "#/$defs/limitValue"
        }
      },
      "evidence": {
        "type": "array",
        "minItems": 1,
        "items": {
          "type": "object",
          "required": [
            "kind",
            "command",
            "result",
            "verified_at"
          ],
          "properties": {
            "kind": {
              "enum": [
                "conformance_suite",
                "test_suite",
                "package_smoke",
                "manual_smoke"
              ]
            },
            "command": {
              "type": "string",
              "minLength": 1
            },
            "result": {
              "const": "pass"
            },
            "verified_at": {
              "type": "string",
              "format": "date-time"
            },
            "artifact": {
              "type": "string",
              "minLength": 1
            },
            "environment": {
              "type": "string",
              "minLength": 1
            }
          },
          "additionalProperties": false
        }
      }
    },
    "patternProperties": {
      "^x-[A-Za-z0-9._:-]+$": true
    },
    "additionalProperties": false,
    "allOf": [
      {
        "if": {
          "properties": {
            "profiles": {
              "contains": {
                "const": "collection_semantics"
              }
            }
          }
        },
        "then": {
          "properties": {
            "profiles": {
              "contains": {
                "const": "core_read"
              }
            }
          }
        }
      },
      {
        "if": {
          "properties": {
            "profiles": {
              "contains": {
                "const": "cel_match"
              }
            }
          }
        },
        "then": {
          "properties": {
            "profiles": {
              "allOf": [
                {
                  "contains": {
                    "const": "core_read"
                  }
                },
                {
                  "contains": {
                    "const": "cel"
                  }
                }
              ]
            }
          }
        }
      },
      {
        "if": {
          "properties": {
            "profiles": {
              "contains": {
                "const": "cel_query"
              }
            }
          }
        },
        "then": {
          "properties": {
            "profiles": {
              "allOf": [
                {
                  "contains": {
                    "const": "core_read"
                  }
                },
                {
                  "contains": {
                    "const": "cel"
                  }
                }
              ]
            }
          }
        }
      },
      {
        "if": {
          "properties": {
            "profiles": {
              "contains": {
                "const": "links"
              }
            }
          }
        },
        "then": {
          "properties": {
            "profiles": {
              "allOf": [
                {
                  "contains": {
                    "const": "collection_semantics"
                  }
                },
                {
                  "contains": {
                    "const": "cel"
                  }
                }
              ]
            }
          }
        }
      },
      {
        "if": {
          "properties": {
            "profiles": {
              "contains": {
                "const": "core_write"
              }
            }
          }
        },
        "then": {
          "properties": {
            "profiles": {
              "contains": {
                "const": "collection_semantics"
              }
            }
          }
        }
      },
      {
        "if": {
          "properties": {
            "profiles": {
              "contains": {
                "const": "lifecycle"
              }
            }
          }
        },
        "then": {
          "properties": {
            "profiles": {
              "allOf": [
                {
                  "contains": {
                    "const": "core_write"
                  }
                },
                {
                  "contains": {
                    "const": "cel"
                  }
                }
              ]
            }
          }
        }
      },
      {
        "if": {
          "properties": {
            "profiles": {
              "contains": {
                "const": "runtime_contracts/0.1"
              }
            }
          }
        },
        "then": {
          "required": [
            "runtime_profile_version"
          ]
        }
      },
      {
        "if": {
          "properties": {
            "profiles": {
              "contains": {
                "const": "workflow/0.1"
              }
            }
          }
        },
        "then": {
          "required": [
            "runtime_profile_version"
          ],
          "properties": {
            "profiles": {
              "allOf": [
                {
                  "contains": {
                    "const": "runtime_contracts/0.1"
                  }
                },
                {
                  "contains": {
                    "const": "cel"
                  }
                }
              ]
            }
          }
        }
      },
      {
        "if": {
          "properties": {
            "profiles": {
              "contains": {
                "const": "watch"
              }
            }
          }
        },
        "then": {
          "properties": {
            "profiles": {
              "contains": {
                "const": "core_read"
              }
            }
          }
        }
      }
    ],
    "$defs": {
      "identifier": {
        "type": "string",
        "pattern": "^[A-Za-z][A-Za-z0-9._:/-]*$"
      },
      "profile": {
        "enum": [
          "core_read",
          "collection_semantics",
          "cel",
          "cel_match",
          "cel_query",
          "links",
          "core_write",
          "lifecycle",
          "runtime_contracts/0.1",
          "workflow/0.1",
          "watch"
        ]
      },
      "limitValue": {
        "oneOf": [
          {
            "type": "string"
          },
          {
            "type": "number"
          },
          {
            "type": "boolean"
          },
          {
            "type": "array",
            "items": {
              "oneOf": [
                {
                  "type": "string"
                },
                {
                  "type": "number"
                },
                {
                  "type": "boolean"
                }
              ]
            }
          }
        ]
      }
    }
  },
  "coreDiagnostic": {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://mdbase.dev/schemas/v0.3/diagnostic.schema.json",
    "title": "mdbase v0.3 diagnostic",
    "type": "object",
    "required": [
      "severity",
      "code",
      "message"
    ],
    "properties": {
      "severity": {
        "enum": [
          "info",
          "warning",
          "error"
        ]
      },
      "code": {
        "type": "string",
        "pattern": "^[a-z][a-z0-9_]*$"
      },
      "message": {
        "type": "string",
        "minLength": 1
      },
      "path": {
        "type": "string",
        "pattern": "^(?!/)(?!.*(?:^|/)\\.\\.(?:/|$))[^\\\\]*$"
      },
      "field": {
        "type": "string"
      },
      "type": {
        "type": "string"
      },
      "schema_location": {
        "type": "string",
        "format": "uri-reference"
      },
      "details": {}
    },
    "patternProperties": {
      "^x-[A-Za-z][A-Za-z0-9._:-]{0,127}$": true
    },
    "additionalProperties": false
  },
  "operationResult": {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://mdbase.dev/schemas/v0.3/operation-result.schema.json",
    "title": "mdbase v0.3 operation result",
    "type": "object",
    "required": [
      "valid",
      "result",
      "diagnostics"
    ],
    "properties": {
      "valid": {
        "type": "boolean"
      },
      "result": {},
      "diagnostics": {
        "type": "array",
        "items": {
          "$ref": "diagnostic.schema.json"
        }
      }
    },
    "additionalProperties": false
  },
  "recordDocument": {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://mdbase.dev/schemas/v0.3/record-document.schema.json",
    "title": "mdbase v0.3 record document",
    "type": "object",
    "required": [
      "path",
      "revision",
      "types",
      "frontmatter",
      "effective_frontmatter",
      "body",
      "file"
    ],
    "properties": {
      "path": {
        "type": "string",
        "minLength": 1
      },
      "revision": {
        "type": "string",
        "minLength": 1
      },
      "types": {
        "type": "array",
        "items": {
          "type": "string",
          "minLength": 1
        }
      },
      "frontmatter": {
        "type": "object"
      },
      "effective_frontmatter": {
        "type": "object"
      },
      "body": {
        "type": "string"
      },
      "document": {
        "type": "string"
      },
      "file": {
        "type": "object",
        "required": [
          "name",
          "folder",
          "size",
          "mtime"
        ],
        "properties": {
          "name": {
            "type": "string",
            "minLength": 1
          },
          "folder": {
            "type": "string"
          },
          "size": {
            "type": "integer",
            "minimum": 0
          },
          "mtime": {
            "type": "string"
          }
        },
        "additionalProperties": false
      }
    },
    "additionalProperties": false
  },
  "queryResult": {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://mdbase.dev/schemas/v0.3/query-result.schema.json",
    "title": "mdbase v0.3 query result",
    "type": "object",
    "required": [
      "results",
      "meta",
      "diagnostics"
    ],
    "properties": {
      "results": {
        "type": "array",
        "items": {
          "type": "object",
          "required": [
            "file"
          ],
          "properties": {
            "file": {
              "type": "object",
              "required": [
                "path"
              ],
              "properties": {
                "path": {
                  "type": "string",
                  "minLength": 1
                }
              },
              "additionalProperties": true
            },
            "frontmatter": {
              "type": "object"
            },
            "effective_frontmatter": {
              "type": "object"
            },
            "values": {
              "type": "object"
            },
            "body": {
              "type": "string"
            }
          },
          "additionalProperties": true
        }
      },
      "meta": {
        "type": "object",
        "required": [
          "total_count",
          "has_more"
        ],
        "properties": {
          "total_count": {
            "type": "integer",
            "minimum": 0
          },
          "has_more": {
            "type": "boolean"
          },
          "context": {
            "type": "object",
            "required": [
              "path"
            ],
            "properties": {
              "path": {
                "type": "string",
                "minLength": 1
              }
            },
            "additionalProperties": false
          },
          "view": {
            "type": "object",
            "required": [
              "path",
              "id"
            ],
            "properties": {
              "path": {
                "type": "string",
                "minLength": 1
              },
              "id": {
                "type": "string",
                "minLength": 1
              }
            },
            "additionalProperties": false
          },
          "groups": {
            "type": "array",
            "items": {
              "$ref": "#/$defs/group"
            }
          }
        },
        "additionalProperties": true
      },
      "diagnostics": {
        "type": "array",
        "items": {
          "$ref": "diagnostic.schema.json"
        }
      }
    },
    "additionalProperties": false,
    "$defs": {
      "group": {
        "type": "object",
        "required": [
          "values",
          "count",
          "summaries"
        ],
        "properties": {
          "values": {
            "type": "object"
          },
          "count": {
            "type": "integer",
            "minimum": 0
          },
          "summaries": {
            "type": "object"
          }
        },
        "additionalProperties": false
      }
    }
  },
  "typeFile": {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://mdbase.dev/schemas/v0.3/type-file.schema.json",
    "title": "mdbase v0.3 type file frontmatter",
    "type": "object",
    "required": [
      "kind",
      "name",
      "schema"
    ],
    "properties": {
      "kind": {
        "const": "mdbase.type"
      },
      "name": {
        "$ref": "#/$defs/typeName"
      },
      "version": {
        "type": "integer",
        "minimum": 1
      },
      "description": {
        "type": "string"
      },
      "match": {
        "$ref": "#/$defs/match"
      },
      "schema": {
        "$ref": "#/$defs/schemaWrapper"
      },
      "collection": {
        "$ref": "#/$defs/collection"
      },
      "lifecycle": {
        "$ref": "#/$defs/lifecycle"
      },
      "runtime": {
        "$ref": "#/$defs/runtime"
      },
      "migrations": {
        "$ref": "#/$defs/migrations"
      },
      "implements": {
        "$ref": "#/$defs/implementations"
      }
    },
    "patternProperties": {
      "^x-[A-Za-z][A-Za-z0-9._:-]{0,127}$": {
        "$ref": "#/$defs/domainExtension"
      }
    },
    "unevaluatedProperties": false,
    "$defs": {
      "typeName": {
        "type": "string",
        "pattern": "^[A-Za-z][A-Za-z0-9_-]{0,127}$"
      },
      "identifier": {
        "type": "string",
        "pattern": "^[A-Za-z][A-Za-z0-9._:-]*$"
      },
      "fieldName": {
        "type": "string",
        "pattern": "^[A-Za-z_][A-Za-z0-9_:-]*$"
      },
      "fieldPath": {
        "type": "string",
        "pattern": "^[A-Za-z_][A-Za-z0-9_:-]*(\\[\\])?(\\.[A-Za-z_][A-Za-z0-9_:-]*(\\[\\])?)*$"
      },
      "jsonPointer": {
        "type": "string",
        "pattern": "^(/([^/~]|~0|~1)*)*$"
      },
      "jsonSchema": {
        "type": "object",
        "additionalProperties": true
      },
      "schemaWrapper": {
        "type": "object",
        "required": [
          "dialect"
        ],
        "properties": {
          "dialect": {
            "const": "json-schema-2020-12"
          },
          "value": {
            "$ref": "#/$defs/jsonSchema"
          },
          "ref": {
            "type": "string",
            "minLength": 1
          }
        },
        "oneOf": [
          {
            "required": [
              "value"
            ],
            "not": {
              "required": [
                "ref"
              ]
            }
          },
          {
            "required": [
              "ref"
            ],
            "not": {
              "required": [
                "value"
              ]
            }
          }
        ],
        "additionalProperties": false
      },
      "match": {
        "type": "object",
        "minProperties": 1,
        "properties": {
          "path_glob": {
            "oneOf": [
              {
                "type": "string",
                "minLength": 1
              },
              {
                "type": "array",
                "minItems": 1,
                "items": {
                  "type": "string",
                  "minLength": 1
                }
              }
            ]
          },
          "fields_present": {
            "type": "array",
            "minItems": 1,
            "items": {
              "$ref": "#/$defs/fieldPath"
            },
            "uniqueItems": true
          },
          "where": {
            "$ref": "#/$defs/matchWhere"
          },
          "expr": {
            "$ref": "#/$defs/expression"
          }
        },
        "additionalProperties": false
      },
      "matchWhere": {
        "type": "object",
        "minProperties": 1,
        "additionalProperties": {
          "$ref": "#/$defs/matchPredicate"
        }
      },
      "matchPredicate": {
        "oneOf": [
          {
            "$ref": "#/$defs/scalar"
          },
          {
            "type": "array"
          },
          {
            "type": "object",
            "properties": {
              "eq": {},
              "neq": {},
              "contains": {},
              "containsAll": {
                "type": "array"
              },
              "containsAny": {
                "type": "array"
              },
              "exists": {
                "type": "boolean"
              },
              "startsWith": {
                "type": "string"
              },
              "endsWith": {
                "type": "string"
              },
              "matches": {
                "type": "string"
              },
              "gt": {
                "$ref": "#/$defs/scalar"
              },
              "gte": {
                "$ref": "#/$defs/scalar"
              },
              "lt": {
                "$ref": "#/$defs/scalar"
              },
              "lte": {
                "$ref": "#/$defs/scalar"
              }
            },
            "minProperties": 1,
            "additionalProperties": false
          }
        ]
      },
      "collection": {
        "type": "object",
        "properties": {
          "display": {
            "$ref": "#/$defs/display"
          },
          "read_defaults": {
            "type": "object",
            "additionalProperties": true
          },
          "links": {
            "$ref": "#/$defs/links"
          },
          "unique": {
            "$ref": "#/$defs/uniqueRules"
          },
          "path": {
            "$ref": "#/$defs/pathPolicy"
          },
          "projections": {
            "$ref": "#/$defs/projections"
          }
        },
        "patternProperties": {
          "^x-[A-Za-z][A-Za-z0-9._:-]{0,127}$": {
            "$ref": "#/$defs/domainExtension"
          }
        },
        "additionalProperties": false
      },
      "display": {
        "type": "object",
        "properties": {
          "name_field": {
            "$ref": "#/$defs/fieldPath"
          },
          "description_field": {
            "$ref": "#/$defs/fieldPath"
          },
          "icon": {
            "type": "string"
          },
          "color_field": {
            "$ref": "#/$defs/fieldPath"
          }
        },
        "additionalProperties": false
      },
      "links": {
        "type": "object",
        "minProperties": 1,
        "propertyNames": {
          "$ref": "#/$defs/fieldPath"
        },
        "additionalProperties": {
          "$ref": "#/$defs/linkRule"
        }
      },
      "linkRule": {
        "type": "object",
        "properties": {
          "target_type": {
            "anyOf": [
              {
                "$ref": "#/$defs/typeName"
              },
              {
                "const": "any"
              },
              {
                "type": "array",
                "minItems": 1,
                "items": {
                  "$ref": "#/$defs/typeName"
                },
                "uniqueItems": true
              }
            ]
          },
          "validate_exists": {
            "type": "boolean"
          },
          "format": {
            "enum": [
              "wikilink",
              "markdown",
              "path",
              "any"
            ]
          }
        },
        "additionalProperties": false
      },
      "uniqueRules": {
        "type": "array",
        "minItems": 1,
        "items": {
          "type": "object",
          "required": [
            "field"
          ],
          "properties": {
            "field": {
              "$ref": "#/$defs/fieldPath"
            },
            "scope": {
              "enum": [
                "collection",
                "type",
                "path_glob"
              ]
            },
            "path_glob": {
              "type": "string",
              "minLength": 1
            }
          },
          "allOf": [
            {
              "if": {
                "properties": {
                  "scope": {
                    "const": "path_glob"
                  }
                },
                "required": [
                  "scope"
                ]
              },
              "then": {
                "required": [
                  "path_glob"
                ]
              }
            }
          ],
          "additionalProperties": false
        }
      },
      "pathPolicy": {
        "type": "object",
        "properties": {
          "pattern": {
            "type": "string",
            "minLength": 1
          },
          "runtime": {
            "$ref": "#/$defs/identifier"
          },
          "template": {
            "type": "string",
            "minLength": 1
          },
          "folder": {
            "type": "string"
          },
          "generated_by": {
            "$ref": "#/$defs/identifier"
          }
        },
        "additionalProperties": false
      },
      "projections": {
        "type": "object",
        "propertyNames": {
          "$ref": "#/$defs/fieldName"
        },
        "additionalProperties": {
          "type": "object",
          "required": [
            "expr"
          ],
          "properties": {
            "expr": {
              "type": "string",
              "minLength": 1
            },
            "description": {
              "type": "string"
            }
          },
          "additionalProperties": false
        }
      },
      "lifecycle": {
        "type": "object",
        "properties": {
          "on_create": {
            "$ref": "#/$defs/lifecycleEvent"
          },
          "on_update": {
            "$ref": "#/$defs/lifecycleEvent"
          },
          "on_delete": {
            "$ref": "#/$defs/lifecycleEvent"
          },
          "on_rename": {
            "$ref": "#/$defs/lifecycleEvent"
          }
        },
        "additionalProperties": false
      },
      "lifecycleEvent": {
        "oneOf": [
          {
            "$ref": "#/$defs/lifecycleAction"
          },
          {
            "type": "array",
            "minItems": 1,
            "items": {
              "$ref": "#/$defs/lifecycleAction"
            }
          }
        ]
      },
      "lifecycleAction": {
        "type": "object",
        "required": [
          "set"
        ],
        "properties": {
          "if": {
            "type": "string",
            "minLength": 1
          },
          "set": {
            "type": "object",
            "minProperties": 1,
            "propertyNames": {
              "$ref": "#/$defs/fieldPath"
            },
            "additionalProperties": {
              "$ref": "#/$defs/lifecycleValue"
            }
          }
        },
        "additionalProperties": false
      },
      "lifecycleValue": {
        "oneOf": [
          {
            "type": "object",
            "required": [
              "now"
            ],
            "properties": {
              "now": {
                "const": true
              }
            },
            "additionalProperties": false
          },
          {
            "type": "object",
            "required": [
              "today"
            ],
            "properties": {
              "today": {
                "const": true
              }
            },
            "additionalProperties": false
          },
          {
            "type": "object",
            "required": [
              "uuid"
            ],
            "properties": {
              "uuid": {
                "const": true
              }
            },
            "additionalProperties": false
          },
          {
            "type": "object",
            "required": [
              "ulid"
            ],
            "properties": {
              "ulid": {
                "const": true
              }
            },
            "additionalProperties": false
          },
          {
            "type": "object",
            "required": [
              "slugify"
            ],
            "properties": {
              "slugify": {
                "$ref": "#/$defs/fieldPath"
              }
            },
            "additionalProperties": false
          },
          {
            "type": "object",
            "required": [
              "copy"
            ],
            "properties": {
              "copy": {
                "$ref": "#/$defs/fieldPath"
              }
            },
            "additionalProperties": false
          },
          {
            "type": "object",
            "required": [
              "literal"
            ],
            "properties": {
              "literal": true
            },
            "additionalProperties": false
          }
        ]
      },
      "runtime": {
        "type": "object",
        "properties": {
          "contracts": {
            "type": "object",
            "properties": {
              "mode": {
                "enum": [
                  "runtime",
                  "materialized",
                  "strict"
                ]
              }
            },
            "additionalProperties": false
          }
        },
        "patternProperties": {
          "^x-[A-Za-z][A-Za-z0-9._:-]{0,127}$": {
            "$ref": "#/$defs/domainExtension"
          }
        },
        "additionalProperties": false
      },
      "migrations": {
        "type": "array",
        "items": {
          "type": "object",
          "required": [
            "from",
            "to"
          ],
          "properties": {
            "from": {
              "type": "integer",
              "minimum": 0
            },
            "to": {
              "type": "integer",
              "minimum": 1
            },
            "steps": {
              "type": "array",
              "items": {
                "type": "object",
                "minProperties": 1,
                "additionalProperties": true
              }
            },
            "action": {
              "$ref": "#/$defs/identifier"
            },
            "description": {
              "type": "string"
            }
          },
          "oneOf": [
            {
              "required": [
                "steps"
              ]
            },
            {
              "required": [
                "action"
              ]
            }
          ],
          "additionalProperties": false
        }
      },
      "implementations": {
        "type": "array",
        "minItems": 1,
        "items": {
          "$ref": "#/$defs/implementation"
        }
      },
      "implementation": {
        "type": "object",
        "required": [
          "contract",
          "version",
          "fields"
        ],
        "properties": {
          "contract": {
            "$ref": "#/$defs/contractId"
          },
          "version": {
            "$ref": "#/$defs/semanticVersion"
          },
          "fields": {
            "type": "object",
            "propertyNames": {
              "$ref": "#/$defs/fieldPath"
            },
            "additionalProperties": {
              "$ref": "#/$defs/fieldPath"
            }
          },
          "binding": {
            "type": "object"
          }
        },
        "patternProperties": {
          "^x-[A-Za-z][A-Za-z0-9._:-]{0,127}$": {
            "$ref": "#/$defs/domainExtension"
          }
        },
        "additionalProperties": false
      },
      "contractId": {
        "type": "string",
        "minLength": 3,
        "maxLength": 128,
        "pattern": "^[a-z][a-z0-9]*(?:[._-][a-z0-9]+)+$"
      },
      "semanticVersion": {
        "type": "string",
        "pattern": "^(0|[1-9][0-9]*)\\.(0|[1-9][0-9]*)\\.(0|[1-9][0-9]*)(?:-[0-9A-Za-z-]+(?:\\.[0-9A-Za-z-]+)*)?(?:\\+[0-9A-Za-z-]+(?:\\.[0-9A-Za-z-]+)*)?$"
      },
      "expression": {
        "type": "object",
        "required": [
          "$expr"
        ],
        "properties": {
          "$expr": {
            "type": "string",
            "minLength": 1
          }
        },
        "additionalProperties": false
      },
      "domainExtension": {
        "type": "object",
        "additionalProperties": true
      },
      "scalar": {
        "type": [
          "string",
          "number",
          "integer",
          "boolean",
          "null"
        ]
      }
    }
  },
  "dataContract": {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://mdbase.dev/schemas/v0.3/data-contract.schema.json",
    "title": "mdbase v0.3 data contract frontmatter",
    "type": "object",
    "required": [
      "kind",
      "id",
      "version",
      "schema"
    ],
    "properties": {
      "kind": {
        "const": "mdbase.contract"
      },
      "id": {
        "$ref": "#/$defs/contractId"
      },
      "version": {
        "$ref": "#/$defs/semanticVersion"
      },
      "name": {
        "type": "string",
        "minLength": 1
      },
      "description": {
        "type": "string"
      },
      "schema": {
        "$ref": "#/$defs/schemaWrapper"
      },
      "binding_schema": {
        "$ref": "#/$defs/schemaWrapper"
      }
    },
    "patternProperties": {
      "^x-[A-Za-z][A-Za-z0-9._:-]{0,127}$": true
    },
    "additionalProperties": false,
    "$defs": {
      "contractId": {
        "type": "string",
        "minLength": 3,
        "maxLength": 128,
        "pattern": "^[a-z][a-z0-9]*(?:[._-][a-z0-9]+)+$"
      },
      "semanticVersion": {
        "type": "string",
        "pattern": "^(0|[1-9][0-9]*)\\.(0|[1-9][0-9]*)\\.(0|[1-9][0-9]*)(?:-[0-9A-Za-z-]+(?:\\.[0-9A-Za-z-]+)*)?(?:\\+[0-9A-Za-z-]+(?:\\.[0-9A-Za-z-]+)*)?$"
      },
      "schemaWrapper": {
        "type": "object",
        "required": [
          "dialect"
        ],
        "properties": {
          "dialect": {
            "const": "json-schema-2020-12"
          },
          "value": {
            "type": "object"
          },
          "ref": {
            "type": "string",
            "minLength": 1
          }
        },
        "oneOf": [
          {
            "required": [
              "value"
            ],
            "properties": {
              "value": true,
              "ref": false
            }
          },
          {
            "required": [
              "ref"
            ],
            "properties": {
              "ref": true,
              "value": false
            }
          }
        ],
        "additionalProperties": false
      }
    }
  },
  "typePack": {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://mdbase.dev/schemas/v0.3/type-pack.schema.json",
    "title": "mdbase v0.3 type pack manifest",
    "type": "object",
    "required": [
      "kind",
      "id",
      "version",
      "resources"
    ],
    "properties": {
      "kind": {
        "const": "mdbase.type-pack"
      },
      "id": {
        "$ref": "#/$defs/packId"
      },
      "version": {
        "$ref": "#/$defs/semanticVersion"
      },
      "name": {
        "type": "string",
        "minLength": 1
      },
      "description": {
        "type": "string"
      },
      "resources": {
        "type": "array",
        "minItems": 1,
        "items": {
          "$ref": "#/$defs/resource"
        }
      }
    },
    "patternProperties": {
      "^x-[A-Za-z][A-Za-z0-9._:-]{0,127}$": true
    },
    "additionalProperties": false,
    "$defs": {
      "packId": {
        "type": "string",
        "minLength": 3,
        "maxLength": 128,
        "pattern": "^[a-z][a-z0-9]*(?:[._-][a-z0-9]+)+$"
      },
      "semanticVersion": {
        "type": "string",
        "pattern": "^(0|[1-9][0-9]*)\\.(0|[1-9][0-9]*)\\.(0|[1-9][0-9]*)(?:-[0-9A-Za-z-]+(?:\\.[0-9A-Za-z-]+)*)?(?:\\+[0-9A-Za-z-]+(?:\\.[0-9A-Za-z-]+)*)?$"
      },
      "safeRelativePath": {
        "type": "string",
        "minLength": 1,
        "pattern": "^(?!/)(?!.*(?:^|/)\\.\\.(?:/|$))(?!.*\\\\).+$"
      },
      "digest": {
        "type": "string",
        "pattern": "^sha256:[0-9a-f]{64}$"
      },
      "resource": {
        "type": "object",
        "required": [
          "kind",
          "source",
          "target",
          "digest"
        ],
        "properties": {
          "kind": {
            "enum": [
              "contract",
              "type",
              "schema"
            ]
          },
          "source": {
            "$ref": "#/$defs/safeRelativePath"
          },
          "target": {
            "$ref": "#/$defs/safeRelativePath"
          },
          "digest": {
            "$ref": "#/$defs/digest"
          }
        },
        "additionalProperties": false
      }
    }
  },
  "provider": {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://mdbase.dev/schemas/runtime/v0.1/provider.schema.json",
    "title": "mdbase runtime provider contract",
    "type": "object",
    "required": [
      "type",
      "id",
      "version",
      "provider_version",
      "name"
    ],
    "properties": {
      "type": {
        "const": "provider"
      },
      "id": {
        "$ref": "#/$defs/identifier"
      },
      "version": {
        "type": "integer",
        "minimum": 1
      },
      "provider_version": {
        "$ref": "#/$defs/semver"
      },
      "name": {
        "type": "string",
        "minLength": 1
      },
      "description": {
        "type": "string"
      },
      "contracts": {
        "type": "object",
        "properties": {
          "events": {
            "$ref": "#/$defs/identifierList"
          },
          "actions": {
            "$ref": "#/$defs/identifierList"
          },
          "capabilities": {
            "$ref": "#/$defs/identifierList"
          },
          "workflows": {
            "$ref": "#/$defs/identifierList"
          }
        },
        "additionalProperties": false
      }
    },
    "patternProperties": {
      "^x-[A-Za-z0-9._:-]+$": true
    },
    "additionalProperties": false,
    "$defs": {
      "identifier": {
        "type": "string",
        "pattern": "^[A-Za-z][A-Za-z0-9._:-]*$"
      },
      "identifierList": {
        "type": "array",
        "uniqueItems": true,
        "items": {
          "$ref": "#/$defs/identifier"
        }
      },
      "semver": {
        "type": "string",
        "pattern": "^(0|[1-9][0-9]*)\\.(0|[1-9][0-9]*)\\.(0|[1-9][0-9]*)(?:-[0-9A-Za-z-]+(?:\\.[0-9A-Za-z-]+)*)?(?:\\+[0-9A-Za-z-]+(?:\\.[0-9A-Za-z-]+)*)?$"
      }
    }
  },
  "action": {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://mdbase.dev/schemas/runtime/v0.1/action.schema.json",
    "title": "mdbase runtime action contract",
    "type": "object",
    "required": [
      "type",
      "id",
      "version",
      "provider",
      "name",
      "schemas"
    ],
    "properties": {
      "type": {
        "const": "action"
      },
      "id": {
        "$ref": "#/$defs/identifier"
      },
      "version": {
        "type": "integer",
        "minimum": 1
      },
      "provider": {
        "$ref": "#/$defs/identifier"
      },
      "name": {
        "type": "string",
        "minLength": 1
      },
      "description": {
        "type": "string"
      },
      "requires": {
        "$ref": "#/$defs/requires"
      },
      "schemas": {
        "type": "object",
        "required": [
          "dialect",
          "input"
        ],
        "properties": {
          "dialect": {
            "const": "json-schema-2020-12"
          },
          "input": {
            "$ref": "#/$defs/jsonSchema"
          },
          "output": {
            "oneOf": [
              {
                "type": "null"
              },
              {
                "$ref": "#/$defs/jsonSchema"
              }
            ]
          }
        },
        "additionalProperties": false
      },
      "effects": {
        "type": "array",
        "uniqueItems": true,
        "items": {
          "$ref": "#/$defs/identifier"
        }
      },
      "emits": {
        "type": "array",
        "uniqueItems": true,
        "items": {
          "$ref": "#/$defs/identifier"
        }
      },
      "dispatch": {
        "$ref": "#/$defs/dispatch"
      },
      "risk": {
        "enum": [
          "low",
          "medium",
          "high",
          "destructive"
        ]
      }
    },
    "patternProperties": {
      "^x-[A-Za-z0-9._:-]+$": true
    },
    "additionalProperties": false,
    "$defs": {
      "identifier": {
        "type": "string",
        "pattern": "^[A-Za-z][A-Za-z0-9._:-]*$"
      },
      "jsonSchema": {
        "type": "object",
        "additionalProperties": true
      },
      "dispatch": {
        "type": "object",
        "properties": {
          "idempotency": {
            "enum": [
              "invocation_id",
              "none"
            ]
          },
          "cancellation": {
            "enum": [
              "cooperative",
              "none"
            ]
          }
        },
        "additionalProperties": false
      },
      "requires": {
        "type": "object",
        "properties": {
          "capabilities": {
            "type": "array",
            "uniqueItems": true,
            "items": {
              "$ref": "#/$defs/identifier"
            }
          },
          "providers": {
            "type": "array",
            "uniqueItems": true,
            "items": {
              "$ref": "#/$defs/providerRequirement"
            }
          }
        },
        "additionalProperties": false
      },
      "providerRequirement": {
        "oneOf": [
          {
            "$ref": "#/$defs/identifier"
          },
          {
            "type": "object",
            "required": [
              "id",
              "version"
            ],
            "properties": {
              "id": {
                "$ref": "#/$defs/identifier"
              },
              "version": {
                "type": "string",
                "minLength": 1
              }
            },
            "additionalProperties": false
          }
        ]
      }
    }
  },
  "event": {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://mdbase.dev/schemas/runtime/v0.1/event.schema.json",
    "title": "mdbase runtime event contract",
    "type": "object",
    "required": [
      "type",
      "id",
      "version",
      "provider",
      "name",
      "schemas"
    ],
    "properties": {
      "type": {
        "const": "event"
      },
      "id": {
        "$ref": "#/$defs/identifier"
      },
      "version": {
        "type": "integer",
        "minimum": 1
      },
      "provider": {
        "$ref": "#/$defs/identifier"
      },
      "name": {
        "type": "string",
        "minLength": 1
      },
      "description": {
        "type": "string"
      },
      "schemas": {
        "type": "object",
        "required": [
          "dialect",
          "payload"
        ],
        "properties": {
          "dialect": {
            "const": "json-schema-2020-12"
          },
          "payload": {
            "$ref": "#/$defs/jsonSchema"
          }
        },
        "additionalProperties": false
      }
    },
    "patternProperties": {
      "^x-[A-Za-z0-9._:-]+$": true
    },
    "additionalProperties": false,
    "$defs": {
      "identifier": {
        "type": "string",
        "pattern": "^[A-Za-z][A-Za-z0-9._:-]*$"
      },
      "jsonSchema": {
        "type": "object",
        "additionalProperties": true
      }
    }
  },
  "capability": {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://mdbase.dev/schemas/runtime/v0.1/capability.schema.json",
    "title": "mdbase runtime capability contract",
    "type": "object",
    "required": [
      "type",
      "id",
      "version",
      "name"
    ],
    "properties": {
      "type": {
        "const": "capability"
      },
      "id": {
        "$ref": "#/$defs/identifier"
      },
      "version": {
        "type": "integer",
        "minimum": 1
      },
      "provider": {
        "$ref": "#/$defs/identifier"
      },
      "name": {
        "type": "string",
        "minLength": 1
      },
      "description": {
        "type": "string"
      },
      "risk": {
        "enum": [
          "low",
          "medium",
          "high",
          "destructive"
        ]
      },
      "effects": {
        "type": "array",
        "uniqueItems": true,
        "items": {
          "$ref": "#/$defs/identifier"
        }
      }
    },
    "patternProperties": {
      "^x-[A-Za-z0-9._:-]+$": true
    },
    "additionalProperties": false,
    "$defs": {
      "identifier": {
        "type": "string",
        "pattern": "^[A-Za-z][A-Za-z0-9._:-]*$"
      }
    }
  },
  "workflow": {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://mdbase.dev/schemas/runtime/v0.1/workflow.schema.json",
    "title": "mdbase runtime workflow record",
    "type": "object",
    "required": [
      "type",
      "id",
      "version",
      "name",
      "enabled",
      "triggers",
      "steps"
    ],
    "properties": {
      "type": {
        "const": "workflow"
      },
      "id": {
        "$ref": "#/$defs/identifier"
      },
      "version": {
        "type": "integer",
        "minimum": 1
      },
      "name": {
        "type": "string",
        "minLength": 1
      },
      "description": {
        "type": "string"
      },
      "enabled": {
        "type": "boolean"
      },
      "requires": {
        "$ref": "#/$defs/requires"
      },
      "vars": {
        "type": "object",
        "additionalProperties": {
          "$ref": "#/$defs/expressionValue"
        }
      },
      "triggers": {
        "type": "array",
        "minItems": 1,
        "items": {
          "$ref": "#/$defs/trigger"
        }
      },
      "if": {
        "$ref": "#/$defs/expression"
      },
      "steps": {
        "type": "array",
        "minItems": 1,
        "items": {
          "$ref": "#/$defs/step"
        }
      },
      "run": {
        "$ref": "#/$defs/runPolicy"
      }
    },
    "patternProperties": {
      "^x-[A-Za-z0-9._:-]+$": true
    },
    "additionalProperties": false,
    "$defs": {
      "identifier": {
        "type": "string",
        "pattern": "^[A-Za-z][A-Za-z0-9._:-]*$"
      },
      "expression": {
        "type": "object",
        "required": [
          "$expr"
        ],
        "properties": {
          "$expr": {
            "type": "string",
            "minLength": 1
          }
        },
        "additionalProperties": false
      },
      "expressionValue": {
        "oneOf": [
          {
            "type": "null"
          },
          {
            "type": "boolean"
          },
          {
            "type": "number"
          },
          {
            "type": "string"
          },
          {
            "$ref": "#/$defs/expression"
          },
          {
            "type": "array",
            "items": {
              "$ref": "#/$defs/expressionValue"
            }
          },
          {
            "type": "object",
            "not": {
              "required": [
                "$expr"
              ]
            },
            "additionalProperties": {
              "$ref": "#/$defs/expressionValue"
            }
          }
        ]
      },
      "requires": {
        "type": "object",
        "properties": {
          "capabilities": {
            "type": "array",
            "uniqueItems": true,
            "items": {
              "$ref": "#/$defs/identifier"
            }
          },
          "providers": {
            "type": "array",
            "uniqueItems": true,
            "items": {
              "$ref": "#/$defs/providerRequirement"
            }
          }
        },
        "additionalProperties": false
      },
      "providerRequirement": {
        "oneOf": [
          {
            "$ref": "#/$defs/identifier"
          },
          {
            "type": "object",
            "required": [
              "id",
              "version"
            ],
            "properties": {
              "id": {
                "$ref": "#/$defs/identifier"
              },
              "version": {
                "type": "string",
                "minLength": 1
              }
            },
            "additionalProperties": false
          }
        ]
      },
      "trigger": {
        "type": "object",
        "required": [
          "id",
          "event"
        ],
        "properties": {
          "id": {
            "$ref": "#/$defs/identifier"
          },
          "event": {
            "$ref": "#/$defs/identifier"
          },
          "if": {
            "$ref": "#/$defs/expression"
          },
          "debounce": {
            "$ref": "#/$defs/duration"
          },
          "minimum_interval": {
            "$ref": "#/$defs/duration"
          }
        },
        "patternProperties": {
          "^x-[A-Za-z0-9._:-]+$": true
        },
        "additionalProperties": false
      },
      "step": {
        "type": "object",
        "required": [
          "id",
          "action"
        ],
        "properties": {
          "id": {
            "$ref": "#/$defs/identifier"
          },
          "action": {
            "$ref": "#/$defs/identifier"
          },
          "name": {
            "type": "string"
          },
          "if": {
            "$ref": "#/$defs/expression"
          },
          "input": {
            "type": "object",
            "additionalProperties": {
              "$ref": "#/$defs/expressionValue"
            }
          },
          "for_each": {
            "type": "object",
            "required": [
              "items"
            ],
            "properties": {
              "items": {
                "$ref": "#/$defs/expressionValue"
              },
              "as": {
                "type": "string",
                "pattern": "^[A-Za-z_][A-Za-z0-9_]*$"
              }
            },
            "additionalProperties": false
          },
          "requires": {
            "$ref": "#/$defs/requires"
          }
        },
        "patternProperties": {
          "^x-[A-Za-z0-9._:-]+$": true
        },
        "additionalProperties": false
      },
      "runPolicy": {
        "type": "object",
        "properties": {
          "execution": {
            "type": "object",
            "properties": {
              "mode": {
                "enum": [
                  "single_executor",
                  "broadcast",
                  "best_effort"
                ]
              }
            },
            "additionalProperties": false
          },
          "idempotency": {
            "type": "object",
            "required": [
              "key"
            ],
            "properties": {
              "key": {
                "$ref": "#/$defs/expressionValue"
              }
            },
            "additionalProperties": false
          },
          "concurrency": {
            "type": "object",
            "properties": {
              "group": {
                "$ref": "#/$defs/expressionValue"
              },
              "policy": {
                "enum": [
                  "skip",
                  "queue",
                  "replace",
                  "allow"
                ]
              }
            },
            "required": [
              "policy"
            ],
            "additionalProperties": false
          },
          "limits": {
            "type": "object",
            "properties": {
              "timeout": {
                "$ref": "#/$defs/duration"
              },
              "max_items": {
                "type": "integer",
                "minimum": 1
              }
            },
            "additionalProperties": false
          },
          "on_error": {
            "enum": [
              "stop",
              "continue"
            ]
          }
        },
        "additionalProperties": false
      },
      "duration": {
        "type": "string",
        "pattern": "^[0-9]+(ms|s|m|h|d)$"
      }
    }
  },
  "runtimePolicy": {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://mdbase.dev/schemas/runtime/v0.1/runtime-policy.schema.json",
    "title": "mdbase runtime policy record",
    "type": "object",
    "required": [
      "type",
      "id",
      "version",
      "name"
    ],
    "properties": {
      "type": {
        "const": "runtime_policy"
      },
      "id": {
        "$ref": "#/$defs/identifier"
      },
      "version": {
        "type": "integer",
        "minimum": 1
      },
      "name": {
        "type": "string",
        "minLength": 1
      },
      "enabled": {
        "type": "boolean"
      },
      "limits": {
        "type": "object",
        "properties": {
          "workflow_timeout": {
            "$ref": "#/$defs/duration"
          },
          "max_concurrent_runs": {
            "type": "integer",
            "minimum": 1
          },
          "max_steps_per_run": {
            "type": "integer",
            "minimum": 1
          },
          "max_items_per_step": {
            "type": "integer",
            "minimum": 1
          }
        },
        "additionalProperties": false
      },
      "capabilities": {
        "type": "object",
        "propertyNames": {
          "$ref": "#/$defs/identifier"
        },
        "additionalProperties": {
          "$ref": "#/$defs/capabilityPolicy"
        }
      },
      "executors": {
        "type": "object",
        "properties": {
          "default": {
            "$ref": "#/$defs/identifier"
          },
          "workflows": {
            "type": "object",
            "propertyNames": {
              "$ref": "#/$defs/identifier"
            },
            "additionalProperties": {
              "$ref": "#/$defs/identifier"
            }
          }
        },
        "additionalProperties": false
      }
    },
    "patternProperties": {
      "^x-[A-Za-z0-9._:-]+$": true
    },
    "additionalProperties": false,
    "$defs": {
      "identifier": {
        "type": "string",
        "pattern": "^[A-Za-z][A-Za-z0-9._:-]*$"
      },
      "duration": {
        "type": "string",
        "pattern": "^[0-9]+(ms|s|m|h|d)$"
      },
      "capabilityMode": {
        "enum": [
          "allow",
          "deny"
        ]
      },
      "capabilityPolicy": {
        "type": "object",
        "properties": {
          "mode": {
            "$ref": "#/$defs/capabilityMode"
          },
          "max_files_per_run": {
            "type": "integer",
            "minimum": 1
          },
          "max_calls_per_run": {
            "type": "integer",
            "minimum": 1
          }
        },
        "patternProperties": {
          "^x-[A-Za-z0-9._:-]+$": true
        },
        "additionalProperties": false
      }
    }
  },
  "run": {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://mdbase.dev/schemas/runtime/v0.1/run.schema.json",
    "title": "mdbase runtime run record",
    "type": "object",
    "required": [
      "type",
      "id",
      "workflow",
      "workflow_version",
      "workflow_revision",
      "registry_revision",
      "trigger",
      "event_id",
      "status",
      "created_at",
      "updated_at"
    ],
    "properties": {
      "type": {
        "const": "runtime_run"
      },
      "id": {
        "$ref": "#/$defs/identifier"
      },
      "workflow": {
        "$ref": "#/$defs/identifier"
      },
      "workflow_version": {
        "type": "integer",
        "minimum": 1
      },
      "workflow_revision": {
        "$ref": "#/$defs/revision"
      },
      "registry_revision": {
        "$ref": "#/$defs/revision"
      },
      "policy_revision": {
        "$ref": "#/$defs/revision"
      },
      "trigger": {
        "$ref": "#/$defs/identifier"
      },
      "event_id": {
        "$ref": "#/$defs/identifier"
      },
      "event_type": {
        "$ref": "#/$defs/identifier"
      },
      "event_cursor": {
        "type": "integer",
        "minimum": 1
      },
      "executor": {
        "$ref": "#/$defs/identifier"
      },
      "idempotency_key": {
        "type": "string"
      },
      "concurrency_group": {
        "type": "string"
      },
      "status": {
        "enum": [
          "queued",
          "running",
          "waiting",
          "succeeded",
          "failed",
          "cancelled",
          "indeterminate"
        ]
      },
      "created_at": {
        "type": "string",
        "format": "date-time"
      },
      "started_at": {
        "type": "string",
        "format": "date-time"
      },
      "timeout_at": {
        "type": "string",
        "format": "date-time"
      },
      "updated_at": {
        "type": "string",
        "format": "date-time"
      },
      "finished_at": {
        "type": "string",
        "format": "date-time"
      },
      "cancel_requested_at": {
        "type": "string",
        "format": "date-time"
      },
      "steps": {
        "type": "array",
        "items": {
          "type": "object",
          "required": [
            "id",
            "action",
            "status"
          ],
          "properties": {
            "id": {
              "$ref": "#/$defs/identifier"
            },
            "action": {
              "$ref": "#/$defs/identifier"
            },
            "action_version": {
              "type": "integer",
              "minimum": 1
            },
            "invocation_id": {
              "$ref": "#/$defs/identifier"
            },
            "attempt": {
              "type": "integer",
              "minimum": 1
            },
            "status": {
              "enum": [
                "pending",
                "running",
                "succeeded",
                "failed",
                "skipped",
                "cancelled",
                "timed_out",
                "indeterminate"
              ]
            },
            "input": {},
            "output": {},
            "receipt": {
              "type": "object",
              "additionalProperties": true
            },
            "error": {
              "type": "object",
              "additionalProperties": true
            },
            "started_at": {
              "type": "string",
              "format": "date-time"
            },
            "finished_at": {
              "type": "string",
              "format": "date-time"
            }
          },
          "patternProperties": {
            "^x-[A-Za-z0-9._:-]+$": true
          },
          "additionalProperties": false
        }
      }
    },
    "patternProperties": {
      "^x-[A-Za-z0-9._:-]+$": true
    },
    "additionalProperties": false,
    "$defs": {
      "identifier": {
        "type": "string",
        "pattern": "^[A-Za-z][A-Za-z0-9._:-]*$"
      },
      "revision": {
        "type": "string",
        "minLength": 8
      }
    }
  },
  "checkpoint": {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://mdbase.dev/schemas/runtime/v0.1/checkpoint.schema.json",
    "title": "mdbase runtime checkpoint record",
    "type": "object",
    "required": [
      "type",
      "id",
      "workflow",
      "status",
      "updated_at",
      "state"
    ],
    "properties": {
      "type": {
        "const": "runtime_checkpoint"
      },
      "id": {
        "$ref": "#/$defs/identifier"
      },
      "workflow": {
        "$ref": "#/$defs/identifier"
      },
      "run": {
        "$ref": "#/$defs/identifier"
      },
      "status": {
        "enum": [
          "open",
          "waiting",
          "ready",
          "completed",
          "failed",
          "cancelled"
        ]
      },
      "updated_at": {
        "type": "string",
        "format": "date-time"
      },
      "state": {
        "type": "object",
        "additionalProperties": true
      },
      "next_step": {
        "$ref": "#/$defs/identifier"
      },
      "revision": {
        "type": "integer",
        "minimum": 1
      },
      "resume_at": {
        "type": "string",
        "format": "date-time"
      },
      "lease": {
        "type": "object",
        "required": [
          "owner",
          "token",
          "expires_at"
        ],
        "properties": {
          "owner": {
            "$ref": "#/$defs/identifier"
          },
          "token": {
            "type": "string",
            "minLength": 16
          },
          "expires_at": {
            "type": "string",
            "format": "date-time"
          }
        },
        "additionalProperties": false
      }
    },
    "patternProperties": {
      "^x-[A-Za-z0-9._:-]+$": true
    },
    "additionalProperties": false,
    "$defs": {
      "identifier": {
        "type": "string",
        "pattern": "^[A-Za-z][A-Za-z0-9._:-]*$"
      }
    }
  },
  "timer": {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://mdbase.dev/schemas/runtime/v0.1/timer.schema.json",
    "title": "mdbase runtime one-shot timer record",
    "type": "object",
    "required": [
      "type",
      "id",
      "generation",
      "status",
      "fire_at",
      "event",
      "created_at",
      "updated_at"
    ],
    "properties": {
      "type": {
        "const": "runtime_timer"
      },
      "id": {
        "$ref": "#/$defs/identifier"
      },
      "generation": {
        "type": "integer",
        "minimum": 1
      },
      "status": {
        "enum": [
          "scheduled",
          "firing",
          "fired",
          "cancelled"
        ]
      },
      "fire_at": {
        "type": "string",
        "format": "date-time"
      },
      "event": {
        "type": "object",
        "required": [
          "type",
          "contract_version",
          "payload"
        ],
        "properties": {
          "type": {
            "$ref": "#/$defs/identifier"
          },
          "contract_version": {
            "type": "integer",
            "minimum": 1
          },
          "payload": {
            "type": "object",
            "additionalProperties": true
          }
        },
        "additionalProperties": false
      },
      "missed_run_policy": {
        "const": "fire_once"
      },
      "created_at": {
        "type": "string",
        "format": "date-time"
      },
      "updated_at": {
        "type": "string",
        "format": "date-time"
      },
      "fired_at": {
        "type": "string",
        "format": "date-time"
      }
    },
    "patternProperties": {
      "^x-[A-Za-z0-9._:-]+$": true
    },
    "additionalProperties": false,
    "$defs": {
      "identifier": {
        "type": "string",
        "pattern": "^[A-Za-z][A-Za-z0-9._:-]*$"
      }
    }
  },
  "diagnostic": {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://mdbase.dev/schemas/runtime/v0.1/diagnostic.schema.json",
    "title": "mdbase runtime diagnostic record",
    "type": "object",
    "required": [
      "type",
      "id",
      "severity",
      "code",
      "message",
      "created_at"
    ],
    "properties": {
      "type": {
        "const": "runtime_diagnostic"
      },
      "id": {
        "$ref": "#/$defs/identifier"
      },
      "severity": {
        "enum": [
          "info",
          "warning",
          "error"
        ]
      },
      "code": {
        "$ref": "#/$defs/identifier"
      },
      "message": {
        "type": "string",
        "minLength": 1
      },
      "created_at": {
        "type": "string",
        "format": "date-time"
      },
      "path": {
        "type": "string"
      },
      "field": {
        "type": "string"
      },
      "workflow": {
        "$ref": "#/$defs/identifier"
      },
      "action": {
        "$ref": "#/$defs/identifier"
      },
      "event": {
        "$ref": "#/$defs/identifier"
      },
      "details": {
        "type": "object",
        "additionalProperties": true
      }
    },
    "patternProperties": {
      "^x-[A-Za-z0-9._:-]+$": true
    },
    "additionalProperties": false,
    "$defs": {
      "identifier": {
        "type": "string",
        "pattern": "^[A-Za-z][A-Za-z0-9._:-]*$"
      }
    }
  },
  "eventEnvelope": {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://mdbase.dev/schemas/runtime/v0.1/event-envelope.schema.json",
    "title": "mdbase runtime event envelope",
    "type": "object",
    "required": [
      "type",
      "contract_version",
      "id",
      "occurred_at",
      "source",
      "payload"
    ],
    "properties": {
      "type": {
        "$ref": "#/$defs/identifier"
      },
      "contract_version": {
        "type": "integer",
        "minimum": 1
      },
      "id": {
        "$ref": "#/$defs/identifier"
      },
      "occurred_at": {
        "type": "string",
        "format": "date-time"
      },
      "source": {
        "type": "object",
        "required": [
          "runtime"
        ],
        "properties": {
          "runtime": {
            "$ref": "#/$defs/identifier"
          },
          "provider": {
            "$ref": "#/$defs/identifier"
          },
          "collection": {
            "type": "string"
          }
        },
        "patternProperties": {
          "^x-[A-Za-z0-9._:-]+$": true
        },
        "additionalProperties": false
      },
      "payload": {
        "type": "object",
        "additionalProperties": true
      },
      "trace": {
        "type": "object",
        "properties": {
          "correlation_id": {
            "$ref": "#/$defs/identifier"
          },
          "causation_id": {
            "$ref": "#/$defs/identifier"
          }
        },
        "patternProperties": {
          "^x-[A-Za-z0-9._:-]+$": true
        },
        "additionalProperties": false
      }
    },
    "additionalProperties": false,
    "$defs": {
      "identifier": {
        "type": "string",
        "pattern": "^[A-Za-z][A-Za-z0-9._:-]*$"
      }
    }
  }
};
